/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Detail,
  ExecutionLockStatusResponse,
  ExecutionResponseDetail,
  GetFigureByPathParams,
  HTTPValidationError,
  ListExecutionsParams,
  ListExecutionsResponse,
} from "../../schemas";

import { customInstance } from "../../lib/custom-instance";
import type { ErrorType } from "../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Fetch a calibration figure by its file path.

Retrieves a PNG image file from the server's filesystem and returns it
as a streaming response.

Parameters
----------
path : str
    Absolute file path to the calibration figure image

Returns
-------
FileResponse
    PNG image data as a file response with media type "image/png"

Raises
------
HTTPException
    404 if the file does not exist at the specified path
 * @summary Get a calibration figure by its path
 */
export const getFigureByPath = (
  params: GetFigureByPathParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/executions/figure`, method: "GET", params, signal },
    options,
  );
};

export const getGetFigureByPathQueryKey = (params?: GetFigureByPathParams) => {
  return [`/executions/figure`, ...(params ? [params] : [])] as const;
};

export const getGetFigureByPathQueryOptions = <
  TData = Awaited<ReturnType<typeof getFigureByPath>>,
  TError = ErrorType<Detail | HTTPValidationError>,
>(
  params: GetFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFigureByPath>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFigureByPathQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFigureByPath>>> = ({
    signal,
  }) => getFigureByPath(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFigureByPath>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetFigureByPathQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFigureByPath>>
>;
export type GetFigureByPathQueryError = ErrorType<Detail | HTTPValidationError>;

export function useGetFigureByPath<
  TData = Awaited<ReturnType<typeof getFigureByPath>>,
  TError = ErrorType<Detail | HTTPValidationError>,
>(
  params: GetFigureByPathParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFigureByPath>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFigureByPath>>,
          TError,
          Awaited<ReturnType<typeof getFigureByPath>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetFigureByPath<
  TData = Awaited<ReturnType<typeof getFigureByPath>>,
  TError = ErrorType<Detail | HTTPValidationError>,
>(
  params: GetFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFigureByPath>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFigureByPath>>,
          TError,
          Awaited<ReturnType<typeof getFigureByPath>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetFigureByPath<
  TData = Awaited<ReturnType<typeof getFigureByPath>>,
  TError = ErrorType<Detail | HTTPValidationError>,
>(
  params: GetFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFigureByPath>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get a calibration figure by its path
 */

export function useGetFigureByPath<
  TData = Awaited<ReturnType<typeof getFigureByPath>>,
  TError = ErrorType<Detail | HTTPValidationError>,
>(
  params: GetFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFigureByPath>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetFigureByPathQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch the current status of the execution lock.

The execution lock prevents concurrent calibration workflows from running
simultaneously. This endpoint checks whether a lock is currently held.

Parameters
----------
ctx : ProjectContext
    Project context with user and project information

Returns
-------
ExecutionLockStatusResponse
    Response containing lock status (True if locked, False if available)
 * @summary Get the execution lock status
 */
export const getExecutionLockStatus = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ExecutionLockStatusResponse>(
    { url: `/executions/lock-status`, method: "GET", signal },
    options,
  );
};

export const getGetExecutionLockStatusQueryKey = () => {
  return [`/executions/lock-status`] as const;
};

export const getGetExecutionLockStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getExecutionLockStatus>>,
  TError = ErrorType<HTTPValidationError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getExecutionLockStatus>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetExecutionLockStatusQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getExecutionLockStatus>>
  > = ({ signal }) => getExecutionLockStatus(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getExecutionLockStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetExecutionLockStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getExecutionLockStatus>>
>;
export type GetExecutionLockStatusQueryError = ErrorType<HTTPValidationError>;

export function useGetExecutionLockStatus<
  TData = Awaited<ReturnType<typeof getExecutionLockStatus>>,
  TError = ErrorType<HTTPValidationError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExecutionLockStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionLockStatus>>,
          TError,
          Awaited<ReturnType<typeof getExecutionLockStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetExecutionLockStatus<
  TData = Awaited<ReturnType<typeof getExecutionLockStatus>>,
  TError = ErrorType<HTTPValidationError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExecutionLockStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionLockStatus>>,
          TError,
          Awaited<ReturnType<typeof getExecutionLockStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetExecutionLockStatus<
  TData = Awaited<ReturnType<typeof getExecutionLockStatus>>,
  TError = ErrorType<HTTPValidationError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExecutionLockStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get the execution lock status
 */

export function useGetExecutionLockStatus<
  TData = Awaited<ReturnType<typeof getExecutionLockStatus>>,
  TError = ErrorType<HTTPValidationError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExecutionLockStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetExecutionLockStatusQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * List executions for a given chip with pagination.

Parameters
----------
ctx : ProjectContext
    Project context with user and project information
chip_id : str
    ID of the chip to fetch executions for
skip : int
    Number of items to skip (default: 0)
limit : int
    Number of items to return (default: 20, max: 100)

Returns
-------
ListExecutionsResponse
    Wrapped list of executions for the chip
 * @summary List executions
 */
export const listExecutions = (
  params: ListExecutionsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListExecutionsResponse>(
    { url: `/executions`, method: "GET", params, signal },
    options,
  );
};

export const getListExecutionsQueryKey = (params?: ListExecutionsParams) => {
  return [`/executions`, ...(params ? [params] : [])] as const;
};

export const getListExecutionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listExecutions>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listExecutions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListExecutionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listExecutions>>> = ({
    signal,
  }) => listExecutions(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listExecutions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListExecutionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listExecutions>>
>;
export type ListExecutionsQueryError = ErrorType<HTTPValidationError>;

export function useListExecutions<
  TData = Awaited<ReturnType<typeof listExecutions>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListExecutionsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listExecutions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExecutions>>,
          TError,
          Awaited<ReturnType<typeof listExecutions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListExecutions<
  TData = Awaited<ReturnType<typeof listExecutions>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listExecutions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExecutions>>,
          TError,
          Awaited<ReturnType<typeof listExecutions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListExecutions<
  TData = Awaited<ReturnType<typeof listExecutions>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listExecutions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List executions
 */

export function useListExecutions<
  TData = Awaited<ReturnType<typeof listExecutions>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listExecutions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListExecutionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Return the execution detail by its ID.

Parameters
----------
execution_id : str
    ID of the execution to fetch
ctx : ProjectContext
    Project context with user and project information

Returns
-------
ExecutionResponseDetail
    Detailed execution information
 * @summary Get an execution by its ID
 */
export const getExecution = (
  executionId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ExecutionResponseDetail>(
    { url: `/executions/${executionId}`, method: "GET", signal },
    options,
  );
};

export const getGetExecutionQueryKey = (executionId?: string) => {
  return [`/executions/${executionId}`] as const;
};

export const getGetExecutionQueryOptions = <
  TData = Awaited<ReturnType<typeof getExecution>>,
  TError = ErrorType<HTTPValidationError>,
>(
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getExecution>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetExecutionQueryKey(executionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getExecution>>> = ({
    signal,
  }) => getExecution(executionId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!executionId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getExecution>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetExecutionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getExecution>>
>;
export type GetExecutionQueryError = ErrorType<HTTPValidationError>;

export function useGetExecution<
  TData = Awaited<ReturnType<typeof getExecution>>,
  TError = ErrorType<HTTPValidationError>,
>(
  executionId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getExecution>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecution>>,
          TError,
          Awaited<ReturnType<typeof getExecution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetExecution<
  TData = Awaited<ReturnType<typeof getExecution>>,
  TError = ErrorType<HTTPValidationError>,
>(
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getExecution>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecution>>,
          TError,
          Awaited<ReturnType<typeof getExecution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetExecution<
  TData = Awaited<ReturnType<typeof getExecution>>,
  TError = ErrorType<HTTPValidationError>,
>(
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getExecution>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get an execution by its ID
 */

export function useGetExecution<
  TData = Awaited<ReturnType<typeof getExecution>>,
  TError = ErrorType<HTTPValidationError>,
>(
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getExecution>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetExecutionQueryOptions(executionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
