/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Detail,
  ExecutionLockStatusResponse,
  FetchFigureByPathParams,
  HTTPValidationError,
} from "../../schemas";

import { customInstance } from "../../lib/custom-instance";
import type { ErrorType } from "../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Fetch a calibration figure by its path.
 * @summary Fetches a calibration figure by its path
 */
export const fetchFigureByPath = (
  params: FetchFigureByPathParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/executions/figure`, method: "GET", params, signal },
    options,
  );
};

export const getFetchFigureByPathQueryKey = (
  params: FetchFigureByPathParams,
) => {
  return [`/api/executions/figure`, ...(params ? [params] : [])] as const;
};

export const getFetchFigureByPathQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchFigureByPath>>,
  TError = ErrorType<Detail | HTTPValidationError>,
>(
  params: FetchFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchFigureByPath>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFetchFigureByPathQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchFigureByPath>>
  > = ({ signal }) => fetchFigureByPath(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchFigureByPath>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchFigureByPathQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchFigureByPath>>
>;
export type FetchFigureByPathQueryError = ErrorType<
  Detail | HTTPValidationError
>;

export function useFetchFigureByPath<
  TData = Awaited<ReturnType<typeof fetchFigureByPath>>,
  TError = ErrorType<Detail | HTTPValidationError>,
>(
  params: FetchFigureByPathParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchFigureByPath>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFigureByPath>>,
          TError,
          Awaited<ReturnType<typeof fetchFigureByPath>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchFigureByPath<
  TData = Awaited<ReturnType<typeof fetchFigureByPath>>,
  TError = ErrorType<Detail | HTTPValidationError>,
>(
  params: FetchFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchFigureByPath>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFigureByPath>>,
          TError,
          Awaited<ReturnType<typeof fetchFigureByPath>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchFigureByPath<
  TData = Awaited<ReturnType<typeof fetchFigureByPath>>,
  TError = ErrorType<Detail | HTTPValidationError>,
>(
  params: FetchFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchFigureByPath>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetches a calibration figure by its path
 */

export function useFetchFigureByPath<
  TData = Awaited<ReturnType<typeof fetchFigureByPath>>,
  TError = ErrorType<Detail | HTTPValidationError>,
>(
  params: FetchFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchFigureByPath>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getFetchFigureByPathQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch the status of the execution lock.
 * @summary Fetches the status of a calibration.
 */
export const fetchExecutionLockStatus = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ExecutionLockStatusResponse>(
    { url: `/api/executions/lock_status`, method: "GET", signal },
    options,
  );
};

export const getFetchExecutionLockStatusQueryKey = () => {
  return [`/api/executions/lock_status`] as const;
};

export const getFetchExecutionLockStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFetchExecutionLockStatusQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchExecutionLockStatus>>
  > = ({ signal }) => fetchExecutionLockStatus(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchExecutionLockStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchExecutionLockStatus>>
>;
export type FetchExecutionLockStatusQueryError = ErrorType<unknown>;

export function useFetchExecutionLockStatus<
  TData = Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
          TError,
          Awaited<ReturnType<typeof fetchExecutionLockStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchExecutionLockStatus<
  TData = Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
          TError,
          Awaited<ReturnType<typeof fetchExecutionLockStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchExecutionLockStatus<
  TData = Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetches the status of a calibration.
 */

export function useFetchExecutionLockStatus<
  TData = Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchExecutionLockStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getFetchExecutionLockStatusQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
