/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    // container: {
    //   center: true,
    //   padding: '2rem',
    //   screens: {
    //     DEFAULT: '100%',
    //     sm: '600px',
    //     md: '728px',
    //     lg: '984px',
    //     xl: '1240px',
    //     '2xl': '1536px',
    //   },
    // },
    extend: {},
  },
  daisyui: {
    themes: [
      {
        // wireframe: {
        //   ...require("daisyui/src/theming/themes")["wireframe"],
        //   primary: "#000000",
        //   secondary: "teal",
        //   accent: "#45E038",
        //   neutral: "teal",
        //   "base-100": "#F1F3F4",
        //   info: "#51d0ff",
        //   success: "#539b00",
        //   warning: "#bd8100",
        //   error: "#ff7487",
        // },
        qiqb: {
          primary: "#000000",
          secondary: "#98A0F7",
          accent: "#45E038",
          neutral: "#98A0F7",
          "base-100": "#F1F3F4",
          info: "#51d0ff",
          success: "#539b00",
          warning: "#bd8100",
          error: "#ff7487",
        },
        qiqbsub: {
          primary: "#98A0F7",
          "primary-content": "#374151",
          secondary: "#45E038",
          "secondary-content": "#374151",
          accent: "#10b981",
          "accent-content": "#374151",
          neutral: "#98A0F7",
          "neutral-content": "#374151",
          "base-100": "#f5f5f4",
          "base-200": "#FFFFFF",
          "base-300": "#f3f4f6",
          "base-content": "#374151",
          info: "#5cb4ff",
          "info-content": "#030c16",
          success: "#00ac87",
          "success-content": "#000b06",
          warning: "#ffad00",
          "warning-content": "#160b00",
          error: "#ff7487",
          "error-content": "#160506",
        },
      },
      "wireframe",
      "nord",
      "dark",
      "dracula",
    ],
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("daisyui"),
    require("daisyui/src/theming/themes"),
  ],
};
