/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChipDatesResponse,
  ChipResponse,
  ExecutionResponseDetail,
  ExecutionResponseSummary,
  FetchTimeseriesTaskResultByTagAndParameterAndQidParams,
  FetchTimeseriesTaskResultByTagAndParameterParams,
  HTTPValidationError,
  LatestTaskGroupedByChipResponse,
  ListMuxResponse,
  MuxDetailResponse,
  TimeSeriesData,
} from "../../schemas";

import { customInstance } from "../../lib/custom-instance";
import type { ErrorType } from "../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Fetch all chips.

Parameters
----------
current_user : User
    Current authenticated user

Returns
-------
list[ChipResponse]
    List of available chips
 * @summary Fetch all chips
 */
export const listChips = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ChipResponse[]>(
    { url: `/api/chip`, method: "GET", signal },
    options,
  );
};

export const getListChipsQueryKey = () => {
  return [`/api/chip`] as const;
};

export const getListChipsQueryOptions = <
  TData = Awaited<ReturnType<typeof listChips>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listChips>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListChipsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listChips>>> = ({
    signal,
  }) => listChips(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listChips>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListChipsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listChips>>
>;
export type ListChipsQueryError = ErrorType<unknown>;

export function useListChips<
  TData = Awaited<ReturnType<typeof listChips>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChips>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChips>>,
          TError,
          Awaited<ReturnType<typeof listChips>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListChips<
  TData = Awaited<ReturnType<typeof listChips>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChips>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChips>>,
          TError,
          Awaited<ReturnType<typeof listChips>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListChips<
  TData = Awaited<ReturnType<typeof listChips>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChips>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch all chips
 */

export function useListChips<
  TData = Awaited<ReturnType<typeof listChips>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChips>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListChipsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch available dates for a chip from execution counter.

Parameters
----------
chip_id : str
    ID of the chip
current_user : User
    Current authenticated user

Returns
-------
list[str]
    List of available dates in ISO format
 * @summary Fetch available dates for a chip
 */
export const fetchChipDates = (
  chipId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ChipDatesResponse>(
    { url: `/api/chip/${chipId}/dates`, method: "GET", signal },
    options,
  );
};

export const getFetchChipDatesQueryKey = (chipId: string) => {
  return [`/api/chip/${chipId}/dates`] as const;
};

export const getFetchChipDatesQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchChipDates>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchChipDates>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFetchChipDatesQueryKey(chipId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchChipDates>>> = ({
    signal,
  }) => fetchChipDates(chipId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!chipId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchChipDates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchChipDatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchChipDates>>
>;
export type FetchChipDatesQueryError = ErrorType<HTTPValidationError>;

export function useFetchChipDates<
  TData = Awaited<ReturnType<typeof fetchChipDates>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchChipDates>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchChipDates>>,
          TError,
          Awaited<ReturnType<typeof fetchChipDates>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchChipDates<
  TData = Awaited<ReturnType<typeof fetchChipDates>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchChipDates>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchChipDates>>,
          TError,
          Awaited<ReturnType<typeof fetchChipDates>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchChipDates<
  TData = Awaited<ReturnType<typeof fetchChipDates>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchChipDates>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch available dates for a chip
 */

export function useFetchChipDates<
  TData = Awaited<ReturnType<typeof fetchChipDates>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchChipDates>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getFetchChipDatesQueryOptions(chipId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch a chip by its ID.

Parameters
----------
chip_id : str
    ID of the chip to fetch
current_user_id : str
    Current user ID from authentication

Returns
-------
ChipResponse
    Chip information
 * @summary Fetch a chip
 */
export const fetchChip = (
  chipId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ChipResponse>(
    { url: `/api/chip/${chipId}`, method: "GET", signal },
    options,
  );
};

export const getFetchChipQueryKey = (chipId: string) => {
  return [`/api/chip/${chipId}`] as const;
};

export const getFetchChipQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchChip>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFetchChipQueryKey(chipId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchChip>>> = ({
    signal,
  }) => fetchChip(chipId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!chipId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof fetchChip>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData>;
  };
};

export type FetchChipQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchChip>>
>;
export type FetchChipQueryError = ErrorType<HTTPValidationError>;

export function useFetchChip<
  TData = Awaited<ReturnType<typeof fetchChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchChip>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchChip>>,
          TError,
          Awaited<ReturnType<typeof fetchChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchChip<
  TData = Awaited<ReturnType<typeof fetchChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchChip>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchChip>>,
          TError,
          Awaited<ReturnType<typeof fetchChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchChip<
  TData = Awaited<ReturnType<typeof fetchChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchChip>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch a chip
 */

export function useFetchChip<
  TData = Awaited<ReturnType<typeof fetchChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchChip>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getFetchChipQueryOptions(chipId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch all executions for a given chip.

Parameters
----------
chip_id : str
    ID of the chip to fetch executions for
current_user : str
    Current user ID from authentication

Returns
-------
list[ExecutionResponseSummary]
    List of executions for the chip
 * @summary Fetch executions
 */
export const listExecutionsByChipId = (
  chipId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ExecutionResponseSummary[]>(
    { url: `/api/chip/${chipId}/execution`, method: "GET", signal },
    options,
  );
};

export const getListExecutionsByChipIdQueryKey = (chipId: string) => {
  return [`/api/chip/${chipId}/execution`] as const;
};

export const getListExecutionsByChipIdQueryOptions = <
  TData = Awaited<ReturnType<typeof listExecutionsByChipId>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listExecutionsByChipId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListExecutionsByChipIdQueryKey(chipId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listExecutionsByChipId>>
  > = ({ signal }) => listExecutionsByChipId(chipId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!chipId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listExecutionsByChipId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListExecutionsByChipIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof listExecutionsByChipId>>
>;
export type ListExecutionsByChipIdQueryError = ErrorType<HTTPValidationError>;

export function useListExecutionsByChipId<
  TData = Awaited<ReturnType<typeof listExecutionsByChipId>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listExecutionsByChipId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExecutionsByChipId>>,
          TError,
          Awaited<ReturnType<typeof listExecutionsByChipId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListExecutionsByChipId<
  TData = Awaited<ReturnType<typeof listExecutionsByChipId>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listExecutionsByChipId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExecutionsByChipId>>,
          TError,
          Awaited<ReturnType<typeof listExecutionsByChipId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListExecutionsByChipId<
  TData = Awaited<ReturnType<typeof listExecutionsByChipId>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listExecutionsByChipId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch executions
 */

export function useListExecutionsByChipId<
  TData = Awaited<ReturnType<typeof listExecutionsByChipId>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listExecutionsByChipId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListExecutionsByChipIdQueryOptions(chipId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Return the execution detail by its ID.

Parameters
----------
chip_id : str
    ID of the chip
execution_id : str
    ID of the execution to fetch
current_user_id : str
    Current user ID from authentication

Returns
-------
ExecutionResponseDetail
    Detailed execution information
 * @summary Fetch an execution by its ID
 */
export const fetchExecutionByChipId = (
  chipId: string,
  executionId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ExecutionResponseDetail>(
    {
      url: `/api/chip/${chipId}/execution/${executionId}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getFetchExecutionByChipIdQueryKey = (
  chipId: string,
  executionId: string,
) => {
  return [`/api/chip/${chipId}/execution/${executionId}`] as const;
};

export const getFetchExecutionByChipIdQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchExecutionByChipId>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchExecutionByChipId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFetchExecutionByChipIdQueryKey(chipId, executionId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchExecutionByChipId>>
  > = ({ signal }) =>
    fetchExecutionByChipId(chipId, executionId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && executionId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchExecutionByChipId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchExecutionByChipIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchExecutionByChipId>>
>;
export type FetchExecutionByChipIdQueryError = ErrorType<HTTPValidationError>;

export function useFetchExecutionByChipId<
  TData = Awaited<ReturnType<typeof fetchExecutionByChipId>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  executionId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchExecutionByChipId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchExecutionByChipId>>,
          TError,
          Awaited<ReturnType<typeof fetchExecutionByChipId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchExecutionByChipId<
  TData = Awaited<ReturnType<typeof fetchExecutionByChipId>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchExecutionByChipId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchExecutionByChipId>>,
          TError,
          Awaited<ReturnType<typeof fetchExecutionByChipId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchExecutionByChipId<
  TData = Awaited<ReturnType<typeof fetchExecutionByChipId>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchExecutionByChipId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch an execution by its ID
 */

export function useFetchExecutionByChipId<
  TData = Awaited<ReturnType<typeof fetchExecutionByChipId>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchExecutionByChipId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getFetchExecutionByChipIdQueryOptions(
    chipId,
    executionId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch the multiplexer details.

Parameters
----------
chip_id : str
    ID of the chip
mux_id : int
    ID of the multiplexer
current_user : User
    Current authenticated user

Returns
-------
MuxDetailResponse
    Multiplexer details
 * @summary Fetch the multiplexer details
 */
export const fetchMuxDetails = (
  chipId: string,
  muxId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<MuxDetailResponse>(
    { url: `/api/chip/${chipId}/mux/${muxId}`, method: "GET", signal },
    options,
  );
};

export const getFetchMuxDetailsQueryKey = (chipId: string, muxId: number) => {
  return [`/api/chip/${chipId}/mux/${muxId}`] as const;
};

export const getFetchMuxDetailsQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchMuxDetails>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  muxId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchMuxDetails>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFetchMuxDetailsQueryKey(chipId, muxId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchMuxDetails>>> = ({
    signal,
  }) => fetchMuxDetails(chipId, muxId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && muxId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchMuxDetails>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchMuxDetailsQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchMuxDetails>>
>;
export type FetchMuxDetailsQueryError = ErrorType<HTTPValidationError>;

export function useFetchMuxDetails<
  TData = Awaited<ReturnType<typeof fetchMuxDetails>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  muxId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchMuxDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchMuxDetails>>,
          TError,
          Awaited<ReturnType<typeof fetchMuxDetails>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchMuxDetails<
  TData = Awaited<ReturnType<typeof fetchMuxDetails>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  muxId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchMuxDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchMuxDetails>>,
          TError,
          Awaited<ReturnType<typeof fetchMuxDetails>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchMuxDetails<
  TData = Awaited<ReturnType<typeof fetchMuxDetails>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  muxId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchMuxDetails>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch the multiplexer details
 */

export function useFetchMuxDetails<
  TData = Awaited<ReturnType<typeof fetchMuxDetails>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  muxId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchMuxDetails>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getFetchMuxDetailsQueryOptions(chipId, muxId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch the multiplexers.

Parameters
----------
chip_id : str
    ID of the chip
current_user : User
    Current authenticated user

Returns
-------
ListMuxResponse
    Multiplexdetails
 * @summary Fetch the multiplexers
 */
export const listMuxes = (
  chipId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListMuxResponse>(
    { url: `/api/chip/${chipId}/mux`, method: "GET", signal },
    options,
  );
};

export const getListMuxesQueryKey = (chipId: string) => {
  return [`/api/chip/${chipId}/mux`] as const;
};

export const getListMuxesQueryOptions = <
  TData = Awaited<ReturnType<typeof listMuxes>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMuxes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMuxesQueryKey(chipId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMuxes>>> = ({
    signal,
  }) => listMuxes(chipId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!chipId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof listMuxes>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData>;
  };
};

export type ListMuxesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMuxes>>
>;
export type ListMuxesQueryError = ErrorType<HTTPValidationError>;

export function useListMuxes<
  TData = Awaited<ReturnType<typeof listMuxes>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMuxes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMuxes>>,
          TError,
          Awaited<ReturnType<typeof listMuxes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListMuxes<
  TData = Awaited<ReturnType<typeof listMuxes>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMuxes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMuxes>>,
          TError,
          Awaited<ReturnType<typeof listMuxes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListMuxes<
  TData = Awaited<ReturnType<typeof listMuxes>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMuxes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch the multiplexers
 */

export function useListMuxes<
  TData = Awaited<ReturnType<typeof listMuxes>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMuxes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListMuxesQueryOptions(chipId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch historical task results for a specific date.

Parameters
----------
chip_id : str
    ID of the chip
task_name : str
    Name of the task to fetch
recorded_date : str
    Date to fetch history for (ISO format YYYY-MM-DD)
current_user : User
    Current authenticated user

Returns
-------
LatestTaskGroupedByChipResponse
    Historical task results for all qubits on the specified date
 * @summary Fetch historical task results
 */
export const fetchHistoricalQubitTaskGroupedByChip = (
  chipId: string,
  taskName: string,
  recordedDate: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LatestTaskGroupedByChipResponse>(
    {
      url: `/api/chip/${chipId}/task/qubit/${taskName}/history/${recordedDate}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getFetchHistoricalQubitTaskGroupedByChipQueryKey = (
  chipId: string,
  taskName: string,
  recordedDate: string,
) => {
  return [
    `/api/chip/${chipId}/task/qubit/${taskName}/history/${recordedDate}`,
  ] as const;
};

export const getFetchHistoricalQubitTaskGroupedByChipQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  recordedDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFetchHistoricalQubitTaskGroupedByChipQueryKey(
      chipId,
      taskName,
      recordedDate,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>
  > = ({ signal }) =>
    fetchHistoricalQubitTaskGroupedByChip(
      chipId,
      taskName,
      recordedDate,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && taskName && recordedDate),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchHistoricalQubitTaskGroupedByChipQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>
>;
export type FetchHistoricalQubitTaskGroupedByChipQueryError =
  ErrorType<HTTPValidationError>;

export function useFetchHistoricalQubitTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  recordedDate: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
          TError,
          Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchHistoricalQubitTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  recordedDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
          TError,
          Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchHistoricalQubitTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  recordedDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch historical task results
 */

export function useFetchHistoricalQubitTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  recordedDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchHistoricalQubitTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getFetchHistoricalQubitTaskGroupedByChipQueryOptions(
    chipId,
    taskName,
    recordedDate,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch the multiplexers.
 * @summary Fetch the multiplexers
 */
export const fetchLatestQubitTaskGroupedByChip = (
  chipId: string,
  taskName: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LatestTaskGroupedByChipResponse>(
    {
      url: `/api/chip/${chipId}/task/qubit/${taskName}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getFetchLatestQubitTaskGroupedByChipQueryKey = (
  chipId: string,
  taskName: string,
) => {
  return [`/api/chip/${chipId}/task/qubit/${taskName}`] as const;
};

export const getFetchLatestQubitTaskGroupedByChipQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFetchLatestQubitTaskGroupedByChipQueryKey(chipId, taskName);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>
  > = ({ signal }) =>
    fetchLatestQubitTaskGroupedByChip(chipId, taskName, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && taskName),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchLatestQubitTaskGroupedByChipQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>
>;
export type FetchLatestQubitTaskGroupedByChipQueryError =
  ErrorType<HTTPValidationError>;

export function useFetchLatestQubitTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
          TError,
          Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchLatestQubitTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
          TError,
          Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchLatestQubitTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch the multiplexers
 */

export function useFetchLatestQubitTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLatestQubitTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getFetchLatestQubitTaskGroupedByChipQueryOptions(
    chipId,
    taskName,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch historical task results for a specific date.

Parameters
----------
chip_id : str
    ID of the chip
task_name : str
    Name of the task to fetch
recorded_date : str
    Date to fetch history for (ISO format YYYY-MM-DD)
current_user : User
    Current authenticated user

Returns
-------
LatestTaskGroupedByChipResponse
    Historical task results for all qubits on the specified date
 * @summary Fetch historical task results
 */
export const fetchHistoricalCouplingTaskGroupedByChip = (
  chipId: string,
  taskName: string,
  recordedDate: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LatestTaskGroupedByChipResponse>(
    {
      url: `/api/chip/${chipId}/task/coupling/${taskName}/history/${recordedDate}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getFetchHistoricalCouplingTaskGroupedByChipQueryKey = (
  chipId: string,
  taskName: string,
  recordedDate: string,
) => {
  return [
    `/api/chip/${chipId}/task/coupling/${taskName}/history/${recordedDate}`,
  ] as const;
};

export const getFetchHistoricalCouplingTaskGroupedByChipQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  recordedDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFetchHistoricalCouplingTaskGroupedByChipQueryKey(
      chipId,
      taskName,
      recordedDate,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>
  > = ({ signal }) =>
    fetchHistoricalCouplingTaskGroupedByChip(
      chipId,
      taskName,
      recordedDate,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && taskName && recordedDate),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchHistoricalCouplingTaskGroupedByChipQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>
>;
export type FetchHistoricalCouplingTaskGroupedByChipQueryError =
  ErrorType<HTTPValidationError>;

export function useFetchHistoricalCouplingTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  recordedDate: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
          TError,
          Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchHistoricalCouplingTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  recordedDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
          TError,
          Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchHistoricalCouplingTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  recordedDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch historical task results
 */

export function useFetchHistoricalCouplingTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  recordedDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchHistoricalCouplingTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getFetchHistoricalCouplingTaskGroupedByChipQueryOptions(
    chipId,
    taskName,
    recordedDate,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch the multiplexers.
 * @summary Fetch the multiplexers
 */
export const fetchLatestCouplingTaskGroupedByChip = (
  chipId: string,
  taskName: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LatestTaskGroupedByChipResponse>(
    {
      url: `/api/chip/${chipId}/task/coupling/${taskName}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getFetchLatestCouplingTaskGroupedByChipQueryKey = (
  chipId: string,
  taskName: string,
) => {
  return [`/api/chip/${chipId}/task/coupling/${taskName}`] as const;
};

export const getFetchLatestCouplingTaskGroupedByChipQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFetchLatestCouplingTaskGroupedByChipQueryKey(chipId, taskName);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>
  > = ({ signal }) =>
    fetchLatestCouplingTaskGroupedByChip(
      chipId,
      taskName,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && taskName),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchLatestCouplingTaskGroupedByChipQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>
>;
export type FetchLatestCouplingTaskGroupedByChipQueryError =
  ErrorType<HTTPValidationError>;

export function useFetchLatestCouplingTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
          TError,
          Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchLatestCouplingTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
          TError,
          Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchLatestCouplingTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch the multiplexers
 */

export function useFetchLatestCouplingTaskGroupedByChip<
  TData = Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLatestCouplingTaskGroupedByChip>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getFetchLatestCouplingTaskGroupedByChipQueryOptions(
    chipId,
    taskName,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch the timeseries task result by tag and parameter for a specific qid.

Returns
-------
    TimeSeriesData: Time series data for the specified qid.
 * @summary Fetch the timeseries task result by tag and parameter for a specific qid
 */
export const fetchTimeseriesTaskResultByTagAndParameterAndQid = (
  chipId: string,
  parameter: string,
  qid: string,
  params: FetchTimeseriesTaskResultByTagAndParameterAndQidParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TimeSeriesData>(
    {
      url: `/api/chip/${chipId}/parameter/${parameter}/qid/${qid}`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getFetchTimeseriesTaskResultByTagAndParameterAndQidQueryKey = (
  chipId: string,
  parameter: string,
  qid: string,
  params: FetchTimeseriesTaskResultByTagAndParameterAndQidParams,
) => {
  return [
    `/api/chip/${chipId}/parameter/${parameter}/qid/${qid}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getFetchTimeseriesTaskResultByTagAndParameterAndQidQueryOptions = <
  TData = Awaited<
    ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  parameter: string,
  qid: string,
  params: FetchTimeseriesTaskResultByTagAndParameterAndQidParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFetchTimeseriesTaskResultByTagAndParameterAndQidQueryKey(
      chipId,
      parameter,
      qid,
      params,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>>
  > = ({ signal }) =>
    fetchTimeseriesTaskResultByTagAndParameterAndQid(
      chipId,
      parameter,
      qid,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && parameter && qid),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<
      ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
    >,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchTimeseriesTaskResultByTagAndParameterAndQidQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>>
  >;
export type FetchTimeseriesTaskResultByTagAndParameterAndQidQueryError =
  ErrorType<HTTPValidationError>;

export function useFetchTimeseriesTaskResultByTagAndParameterAndQid<
  TData = Awaited<
    ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  parameter: string,
  qid: string,
  params: FetchTimeseriesTaskResultByTagAndParameterAndQidParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
          >,
          TError,
          Awaited<
            ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchTimeseriesTaskResultByTagAndParameterAndQid<
  TData = Awaited<
    ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  parameter: string,
  qid: string,
  params: FetchTimeseriesTaskResultByTagAndParameterAndQidParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
          >,
          TError,
          Awaited<
            ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchTimeseriesTaskResultByTagAndParameterAndQid<
  TData = Awaited<
    ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  parameter: string,
  qid: string,
  params: FetchTimeseriesTaskResultByTagAndParameterAndQidParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch the timeseries task result by tag and parameter for a specific qid
 */

export function useFetchTimeseriesTaskResultByTagAndParameterAndQid<
  TData = Awaited<
    ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  parameter: string,
  qid: string,
  params: FetchTimeseriesTaskResultByTagAndParameterAndQidParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameterAndQid>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions =
    getFetchTimeseriesTaskResultByTagAndParameterAndQidQueryOptions(
      chipId,
      parameter,
      qid,
      params,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch the timeseries task result by tag and parameter for all qids.

Returns
-------
    TimeSeriesData: Time series data for all qids.
 * @summary Fetch the timeseries task result by tag and parameter for all qids
 */
export const fetchTimeseriesTaskResultByTagAndParameter = (
  chipId: string,
  parameter: string,
  params: FetchTimeseriesTaskResultByTagAndParameterParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TimeSeriesData>(
    {
      url: `/api/chip/${chipId}/parameter/${parameter}`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getFetchTimeseriesTaskResultByTagAndParameterQueryKey = (
  chipId: string,
  parameter: string,
  params: FetchTimeseriesTaskResultByTagAndParameterParams,
) => {
  return [
    `/api/chip/${chipId}/parameter/${parameter}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getFetchTimeseriesTaskResultByTagAndParameterQueryOptions = <
  TData = Awaited<
    ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  parameter: string,
  params: FetchTimeseriesTaskResultByTagAndParameterParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFetchTimeseriesTaskResultByTagAndParameterQueryKey(
      chipId,
      parameter,
      params,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>>
  > = ({ signal }) =>
    fetchTimeseriesTaskResultByTagAndParameter(
      chipId,
      parameter,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && parameter),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchTimeseriesTaskResultByTagAndParameterQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>>
>;
export type FetchTimeseriesTaskResultByTagAndParameterQueryError =
  ErrorType<HTTPValidationError>;

export function useFetchTimeseriesTaskResultByTagAndParameter<
  TData = Awaited<
    ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  parameter: string,
  params: FetchTimeseriesTaskResultByTagAndParameterParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>
          >,
          TError,
          Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchTimeseriesTaskResultByTagAndParameter<
  TData = Awaited<
    ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  parameter: string,
  params: FetchTimeseriesTaskResultByTagAndParameterParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>
          >,
          TError,
          Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchTimeseriesTaskResultByTagAndParameter<
  TData = Awaited<
    ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  parameter: string,
  params: FetchTimeseriesTaskResultByTagAndParameterParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch the timeseries task result by tag and parameter for all qids
 */

export function useFetchTimeseriesTaskResultByTagAndParameter<
  TData = Awaited<
    ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  chipId: string,
  parameter: string,
  params: FetchTimeseriesTaskResultByTagAndParameterParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchTimeseriesTaskResultByTagAndParameter>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions =
    getFetchTimeseriesTaskResultByTagAndParameterQueryOptions(
      chipId,
      parameter,
      params,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
