title = "QDash Gitleaks Configuration"

[extend]
  useDefault = true

[allowlist]
  description = "Global allowlist"
  paths = [
    '''\.devcontainer/requirements\.txt''',
    '''ui/bun\.lock''',
    '''docs/oas/openapi\.json''',
    '''ui/src/client/''',
    '''ui/src/schemas/''',
  ]
  regexTarget = "match"
  regexes = [
    '''mongodb://root:example@mongo:27017''',
  ]
