package_name_override: "qdash_client"
class_name_override: "QDashClient"
custom_templates: "templates/"
post_hooks:
  - "ruff format qdash_client/ || true"
  - "ruff check --fix qdash_client/ || true"
overrides:
  skip_validation: false
  skip_helpers: false
  skip_readme: false
  skip_gitignore: true
