# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference
#
# Coverage exclusions are defined in pyproject.toml [tool.coverage.run]
# so they apply to both local testing and Codecov reporting.

coverage:
  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        target: 50%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
