services:
  devcontainer:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    env_file:
      - .env
    command: sleep infinity
    container_name: qdash-devcontainer
    volumes:
      - .:/workspace/qdash
      - /var/run/docker.sock:/var/run/docker.sock
      # - /workspace/qdash/.venv
      # - /workspace/qdash/ui/node_modules
      # - /home/shared/config:/home/shared/config
    environment:
      - PYTHONPATH=/workspace:/workspace/src:/workspace/src/qdash/workflow:/workspace/src/qdash/dbmodel:/workspace/src/qdash/datamodel:/workspace/src/qdash/neodbmodel
    network_mode: host

    develop:
      watch:
        - action: sync
          path: ./src/qdash/api
          target: /workspace/qdash/api
    working_dir: /workspace/qdash
# if following feature is enabled, this file should be moved to .devcontainer/compose.yaml
# https://github.com/microsoft/vscode-remote-release/issues/4885
