version: 3

env:
  UV_LINK_MODE: copy

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task -l

  generate:
    dir: ui
    dotenv: [.env]
    cmds:
      - curl http://api:$API_PORT/openapi.json | jq > ../docs/oas/openapi.json
      - bunx orval@7.14.0 --config ./orval.config.cjs
      - task fmt-ui
    desc: Generate the TypeScript client

  generate-python-client:
    dotenv: [.env]
    cmds:
      - python -m qdash.scripts.generate_client
    desc: Generate Python client from OpenAPI spec

  docs:
    dir: docs
    cmds:
      - npm run docs:dev

  test:
    cmds:
      - python -m pytest tests/ -v
    desc: Run all tests with pytest

  test-api:
    cmds:
      - python -m pytest tests/qdash/api/ -v
    desc: Run API router tests

  test-dbmodel:
    cmds:
      - python -m pytest tests/qdash/dbmodel/ -v
    desc: Run database model tests

  test-workflow:
    cmds:
      - python -m pytest tests/qdash/workflow/ -v
    desc: Run workflow tests

  test-coverage:
    cmds:
      - python -m pytest tests/ --cov=src/qdash --cov-report=term --cov-report=html
    desc: Run tests with coverage report

  test-fast:
    cmds:
      - python -m pytest tests/ -v -x --tb=short
    desc: Run tests, stop on first failure

  test-mypy:
    cmds:
      - python -m mypy tests/
    desc: Run mypy type checking on tests

  build:
    dir: ui
    cmds:
      - bun run build

  build-docs:
    dir: docs
    cmds:
      - npm run docs:build

  fmt-ui:
    dir: ui
    cmds:
      - bunx prettier . --write
      - bunx eslint . --fix -c eslint.config.js
    desc: Format the UI code

  fmt:
    cmds:
      - uv run ruff format . # Excludes generated client (see pyproject.toml)
      - npx prettier . --write
    desc: Format common code

  fmt-python:
    cmds:
      - uv run ruff format . # Excludes generated client (see pyproject.toml)
    desc: Format Python code only

  lint:
    cmds:
      - uv run ruff check . # Excludes generated client (see pyproject.toml)
      - uv run ruff format --check .
    desc: Run linting checks

  lint-mypy:
    cmds:
      - uv run mypy src/qdash/dbmodel --ignore-missing-imports
    desc: Run mypy type checking on clean modules only

  tbls-docs:
    cmds:
      - tbls doc -c .tbls.yml -f
    desc: Generate DB Schema Docs

  export-api:
    cmds:
      - uv export --group api --no-hashes --no-dev --no-emit-project --no-editable --format requirements-txt > ./src/qdash/api/requirements.txt
    desc: Export server requirements

  export-workflow:
    cmds:
      - uv export --group workflow --no-hashes --no-dev --no-emit-project --no-editable --format requirements-txt > ./src/qdash/workflow/requirements.txt
    desc: Export qcflow requirements

  export-dev:
    cmds:
      - uv export --all-groups --no-hashes --no-emit-project --no-editable --format requirements-txt > .devcontainer/requirements.txt
    desc: Export all requirements

  export-agent:
    cmds:
      - uv export --group agent --no-hashes --no-dev --no-emit-project --no-editable --format requirements-txt > ./src/qdash/slack_agent/requirements.txt
    desc: Export agent requirements
  export-all:
    cmds:
      - task export-api
      - task export-workflow
      - task export-dev
      - task export-agent
    desc: Export all requirements

  build-api:
    cmds:
      - task export-api
      - docker compose build --no-cache api

  build-workflow:
    cmds:
      - task export-workflow
      - docker compose build --no-cache workflow
