version: 3

env:
  UV_LINK_MODE: copy

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task -l

  restart-api:
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - echo "tRestarting API service..."
      - docker compose restart api
    desc: Restart the API service

  generate:
    dir: ui
    dotenv: [.env]
    cmds:
      - docker compose -f ../compose.yaml restart api && sleep 2
      - curl http://api:$API_PORT/openapi.json | jq > ../docs/oas/openapi.json
      - bunx orval@7.14.0 --config ./orval.config.cjs
      - bunx prettier . --write --log-level error
      - bunx eslint . --fix -c eslint.config.mjs --quiet
    desc: Generate the TypeScript client

  docs:
    dir: docs
    cmds:
      - bun install
      - bun run docs:dev --host

  test:
    cmds:
      - python -m pytest tests/ -v
    desc: Run all tests with pytest

  test-api:
    cmds:
      - python -m pytest tests/qdash/api/ -v
    desc: Run API router tests

  test-dbmodel:
    cmds:
      - python -m pytest tests/qdash/dbmodel/ -v
    desc: Run database model tests

  test-workflow:
    cmds:
      - python -m pytest tests/qdash/workflow/ -v
    desc: Run workflow tests

  test-coverage:
    cmds:
      - python -m pytest tests/ --cov=src/qdash --cov-report=term --cov-report=html
    desc: Run tests with coverage report

  test-fast:
    cmds:
      - python -m pytest tests/ -v -x --tb=short
    desc: Run tests, stop on first failure

  test-mypy:
    cmds:
      - python -m mypy tests/
    desc: Run mypy type checking on tests

  build:
    dir: ui
    cmds:
      - bun run build

  build-docs:
    dir: docs
    cmds:
      - npm run docs:build

  lint:
    desc: Run all linting and formatting (Python + UI)
    cmds:
      - task: lint-python
      - task: lint-ui

  lint-python:
    desc: Run Python linting and formatting
    cmds:
      - uv run ruff check --fix --quiet . # Excludes generated client (see pyproject.toml)
      - uv run ruff format --quiet .

  lint-ui:
    dir: ui
    desc: Run UI linting and formatting
    cmds:
      - bunx prettier . --write --log-level error
      - bunx eslint . --fix -c eslint.config.mjs --quiet

  lint-mypy:
    desc: Run mypy strict type checking
    cmds:
      - uv run mypy src/qdash/datamodel src/qdash/dbmodel src/qdash/api src/qdash/workflow

  tbls-docs:
    cmds:
      - tbls doc -c .tbls.yml -f
    desc: Generate DB Schema Docs

  export-api:
    cmds:
      - uv export --group api --no-hashes --no-dev --no-emit-project --no-editable --format requirements-txt > ./src/qdash/api/requirements.txt
    desc: Export server requirements

  export-workflow:
    cmds:
      - uv export --group workflow --no-hashes --no-dev --no-emit-project --no-editable --format requirements-txt > ./src/qdash/workflow/requirements.txt
    desc: Export qcflow requirements

  export-dev:
    cmds:
      - uv export --all-groups --no-hashes --no-emit-project --no-editable --format requirements-txt > .devcontainer/requirements.txt
    desc: Export all requirements

  export-all:
    cmds:
      - task export-api
      - task export-workflow
      - task export-dev
    desc: Export all requirements

  build-api:
    cmds:
      - task export-api
      - docker compose build --no-cache api

  build-workflow:
    cmds:
      - task export-workflow
      - docker compose build --no-cache workflow

  deploy-local:
    cmds:
      - docker compose up -d --build
    desc: Deploy the application with Docker Compose in dev mode

  deploy:
    cmds:
      - docker compose --profile tunnel up -d --build
      - sleep 3
      - docker compose restart api
    desc: Deploy the application with Docker Compose
