/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * QDash Server
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { OneQubitCalibDataAverageGateFidelity } from "./oneQubitCalibDataAverageGateFidelity";
import type { OneQubitCalibDataQubitFrequency } from "./oneQubitCalibDataQubitFrequency";
import type { OneQubitCalibDataResonatorFrequency } from "./oneQubitCalibDataResonatorFrequency";
import type { OneQubitCalibDataT1 } from "./oneQubitCalibDataT1";
import type { OneQubitCalibDataT2Echo } from "./oneQubitCalibDataT2Echo";
import type { OneQubitCalibDataT2Star } from "./oneQubitCalibDataT2Star";

export interface OneQubitCalibData {
  average_gate_fidelity?: OneQubitCalibDataAverageGateFidelity;
  qubit_frequency?: OneQubitCalibDataQubitFrequency;
  resonator_frequency?: OneQubitCalibDataResonatorFrequency;
  t1?: OneQubitCalibDataT1;
  t2_echo?: OneQubitCalibDataT2Echo;
  t2_star?: OneQubitCalibDataT2Star;
}
