/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * QDash Server
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { NodeInfo } from "./nodeInfo";
import type { OneQubitCalibResponseOneQubitCalibData } from "./oneQubitCalibResponseOneQubitCalibData";

export interface OneQubitCalibResponse {
  qpu_name: string;
  cooling_down_id: number;
  label: string;
  status: string;
  node_info: NodeInfo;
  one_qubit_calib_data: OneQubitCalibResponseOneQubitCalibData;
  created_at?: string;
  updated_at?: string;
}
