/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * QDash Server
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { OneQubitCalibHistoryResponseOneQubitCalibData } from "./oneQubitCalibHistoryResponseOneQubitCalibData";

export interface OneQubitCalibHistoryResponse {
  cooling_down_id: number;
  created_at?: string;
  date: string;
  label: string;
  one_qubit_calib_data: OneQubitCalibHistoryResponseOneQubitCalibData;
  qpu_name: string;
  updated_at?: string;
}
