/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * QDash Server
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ParamDataUnit } from "./paramDataUnit";

export interface ParamData {
  label: string;
  unit?: ParamDataUnit;
  value: number;
}
