/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * QDash Server
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ExecuteCalibRequest } from "./executeCalibRequest";

export interface ScheduleCalibResponse {
  menu_name: string;
  menu: ExecuteCalibRequest;
  description: string;
  note: string;
  timezone: string;
  scheduled_time: string;
  flow_run_id: string;
}
