/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * QDash Server
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { TwoQubitCalibDataAverageGateFidelity } from "./twoQubitCalibDataAverageGateFidelity";
import type { TwoQubitCalibDataCrossResonancePower } from "./twoQubitCalibDataCrossResonancePower";

export interface TwoQubitCalibData {
  average_gate_fidelity?: TwoQubitCalibDataAverageGateFidelity;
  cross_resonance_power?: TwoQubitCalibDataCrossResonancePower;
}
