/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { AiReviewListItem } from './aiReviewListItem';
import type { AiReviewRunSummary } from './aiReviewRunSummary';

/**
 * Detail response for one AI review run.
 */
export interface AiReviewRunDetailResponse {
  run: AiReviewRunSummary;
  items: AiReviewListItem[];
}
