/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Base64-encoded result figure (for multimodal analysis)
 */
export type AnalyzeRequestImageBase64 = string | null;
