/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Dispatch a committed candidate for worker-side backend application.
 */
export interface ApplyAgentCandidateRequest {
  /**
     * @minLength 1
     * @maxLength 128
     */
  idempotency_key: string;
  /** @minimum 0 */
  expected_state_version: number;
  push_to_github?: boolean;
}
