/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * The user's decision on a write operation the assistant asked approval for.
 */
export interface ApprovalDecision {
  /** Tool call id from the approval card */
  id: string;
  approve: boolean;
}
