/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ArtifactPreviewResponseTarget } from './artifactPreviewResponseTarget';
import type { ArtifactPreviewResponseSourceType } from './artifactPreviewResponseSourceType';
import type { ArtifactPreviewResponseRowsItem } from './artifactPreviewResponseRowsItem';

/**
 * Tabular preview of a NetCDF calibration artifact.
 */
export interface ArtifactPreviewResponse {
  filename: string;
  target?: ArtifactPreviewResponseTarget;
  source_type?: ArtifactPreviewResponseSourceType;
  shape: number[];
  dtype: string;
  columns: string[];
  rows: ArtifactPreviewResponseRowsItem[];
  total_rows: number;
  truncated: boolean;
}
