/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { BulkAiReviewRequestDate } from './bulkAiReviewRequestDate';
import type { BulkAiReviewRequestModelOverride } from './bulkAiReviewRequestModelOverride';
import type { BulkAiReviewRequestTaskIds } from './bulkAiReviewRequestTaskIds';

/**
 * Request body for bulk AI review.
 */
export interface BulkAiReviewRequest {
  chip_id: string;
  task: string;
  entity_type?: string;
  date?: BulkAiReviewRequestDate;
  task_ids?: BulkAiReviewRequestTaskIds;
  model_override?: BulkAiReviewRequestModelOverride;
}
