/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { BulkUserImportResult } from "./bulkUserImportResult";

/**
 * Response for bulk user import.
 */
export interface BulkUserImportResponse {
  results: BulkUserImportResult[];
  created: number;
  skipped: number;
  failed: number;
  total: number;
}
