/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ChatImageAttachmentMimeType } from './chatImageAttachmentMimeType';

/**
 * One figure the user attached to a chat message.
 */
export interface ChatImageAttachment {
  /**
     * Base64 image bytes without a data: prefix
     * @minLength 1
     * @maxLength 6291456
     */
  data: string;
  mimeType: ChatImageAttachmentMimeType;
}
