/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ChipMetricsResponseCouplingMetrics } from './chipMetricsResponseCouplingMetrics';
import type { ChipMetricsResponseEndAt } from './chipMetricsResponseEndAt';
import type { ChipMetricsResponseQubitMetrics } from './chipMetricsResponseQubitMetrics';
import type { ChipMetricsResponseStartAt } from './chipMetricsResponseStartAt';
import type { ChipMetricsResponseWithinHours } from './chipMetricsResponseWithinHours';

/**
 * Complete chip metrics response.
 */
export interface ChipMetricsResponse {
  chip_id: string;
  username: string;
  qubit_count: number;
  within_hours?: ChipMetricsResponseWithinHours;
  start_at?: ChipMetricsResponseStartAt;
  end_at?: ChipMetricsResponseEndAt;
  qubit_metrics: ChipMetricsResponseQubitMetrics;
  coupling_metrics: ChipMetricsResponseCouplingMetrics;
}
