/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Optional CR direction filter. forward uses the topology coupling order; inverse uses the reverse order; mix returns both available calibrated directions. When omitted, mix is used.
 */
export type ConditionCrDirection = typeof ConditionCrDirection[keyof typeof ConditionCrDirection] | null;


export const ConditionCrDirection = {
  forward: 'forward',
  inverse: 'inverse',
  mix: 'mix',
} as const;
