/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { FidelityCondition } from './fidelityCondition';
import type { ConditionCrDirection } from './conditionCrDirection';

/**
 * Condition for filtering device topology.
 */
export interface Condition {
  coupling_fidelity: FidelityCondition;
  qubit_fidelity: FidelityCondition;
  readout_fidelity: FidelityCondition;
  /** Optional CR direction filter. forward uses the topology coupling order; inverse uses the reverse order; mix returns both available calibrated directions. When omitted, mix is used. */
  cr_direction?: ConditionCrDirection;
  only_maximum_connected?: boolean;
}
