/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Markdown export of the wiring document (derived from wiring_blocks)
 */
export type CooldownUpdateRequestWiringInfo = string | null;
