/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { CopilotChatSessionSummaryContextAnyOf } from './copilotChatSessionSummaryContextAnyOf';

export type CopilotChatSessionSummaryContext = CopilotChatSessionSummaryContextAnyOf | null;
