/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { CopilotChatMessageSchema } from './copilotChatMessageSchema';
import type { CopilotChatSessionResponseContext } from './copilotChatSessionResponseContext';

/**
 * Full session payload returned to the client.
 */
export interface CopilotChatSessionResponse {
  session_id: string;
  title: string;
  context?: CopilotChatSessionResponseContext;
  messages?: CopilotChatMessageSchema[];
  created_at: string;
  updated_at: string;
}
