/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { CouplingMetricsZx90GateFidelity } from "./couplingMetricsZx90GateFidelity";
import type { CouplingMetricsBellStateFidelity } from "./couplingMetricsBellStateFidelity";
import type { CouplingMetricsStaticZzInteraction } from "./couplingMetricsStaticZzInteraction";

/**
 * Two-qubit coupling metrics data.
 */
export interface CouplingMetrics {
  zx90_gate_fidelity?: CouplingMetricsZx90GateFidelity;
  bell_state_fidelity?: CouplingMetricsBellStateFidelity;
  static_zz_interaction?: CouplingMetricsStaticZzInteraction;
}
