/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { AgentSessionPolicy } from './agentSessionPolicy';

/**
 * Create a bounded authorization session for a local agent.
 */
export interface CreateAgentSessionRequest {
  /**
   * @minLength 1
   * @maxLength 200
   */
  chip_id: string;
  policy: AgentSessionPolicy;
  /**
   * @minimum 60
   * @maximum 86400
   */
  expires_in_seconds?: number;
  /** @maxLength 200 */
  skill_name?: string;
  /** @maxLength 200 */
  skill_version?: string;
  /** @maxLength 256 */
  skill_hash?: string;
  /** @maxLength 300 */
  model_name?: string;
}
