/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type CreateMenuRequestTaskDetailsAnyOf = { [key: string]: unknown };
