/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { CryostatCreateRequestCommissionedAt } from './cryostatCreateRequestCommissionedAt';

/**
 * Body for creating a cryostat.
 */
export interface CryostatCreateRequest {
  /**
     * Project-unique identifier
     * @maxLength 100
     */
  cryo_id: string;
  /** @maxLength 200 */
  name?: string;
  /** @maxLength 200 */
  manufacturer?: string;
  /** @maxLength 200 */
  model?: string;
  /** @maxLength 200 */
  location?: string;
  /** active | maintenance | decommissioned */
  status?: string;
  commissioned_at?: CryostatCreateRequestCommissionedAt;
}
