/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type DashboardInsightConfidence =
  (typeof DashboardInsightConfidence)[keyof typeof DashboardInsightConfidence];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardInsightConfidence = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;
