/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { DashboardInsight } from './dashboardInsight';
import type { DashboardInsightSuppressed } from './dashboardInsightSuppressed';

/**
 * Dashboard-level AI insight response.
 */
export interface DashboardAiInsightsResponse {
  chip_id: string;
  summary: string;
  insights?: DashboardInsight[];
  suppressed?: DashboardInsightSuppressed;
}
