/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * A simple message response.
 *
 * Args:
 * ----
 *     BaseModel: The base class for Pydantic models.
 *
 * Attributes:
 * ----------
 *     message (str): The message to return.
 */
export interface Detail {
  detail: string;
}
