/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { Coupling } from './coupling';
import type { Qubit } from './qubit';

/**
 * Device information.
 */
export interface Device {
  name: string;
  device_id: string;
  qubits: Qubit[];
  couplings: Coupling[];
  calibrated_at: string;
}
