/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type DownloadMetricsPdfSelectionMode = typeof DownloadMetricsPdfSelectionMode[keyof typeof DownloadMetricsPdfSelectionMode];


export const DownloadMetricsPdfSelectionMode = {
  latest: 'latest',
  best: 'best',
  average: 'average',
} as const;
