/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type DownloadArtifactsAsArchiveParams = {
/**
 * @minItems 1
 * @maxItems 100
 */
paths: string[];
};
