/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Evaluate one numeric candidate against session-owned parameter bounds.
 */
export interface EvaluateCandidateGateRequest {
  /**
   * @minLength 1
   * @maxLength 200
   */
  parameter_name: string;
  value: number;
}
