/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ExecutePipelineResponseTargets } from './executePipelineResponseTargets';
import type { ResolvedPipelineStep } from './resolvedPipelineStep';

/**
 * Dispatch result plus the resolved plan that was started.
 */
export interface ExecutePipelineResponse {
  /** QDash execution ID (falls back to the Prefect flow run ID when no execution row could be pre-created) */
  execution_id: string;
  /** Prefect flow run ID */
  flow_run_id: string;
  /** Prefect flow run URL */
  flow_run_url: string;
  /** QDash UI URL for execution */
  qdash_ui_url: string;
  /** Success message */
  message: string;
  steps?: ResolvedPipelineStep[];
  targets?: ExecutePipelineResponseTargets;
}
