/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * ExecuteCalibResponse is a subclass of BaseModel.
 */
export interface ExecuteCalibResponse {
  flow_run_url: string;
  qdash_ui_url: string;
}
