/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type FetchTimeseriesTaskResultByTagAndParameterAndQidParams = {
  tag: string;
  start_at: string;
  end_at: string;
};
