/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Thread workflow status
 */
export type ForumPostResponseStatus = typeof ForumPostResponseStatus[keyof typeof ForumPostResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ForumPostResponseStatus = {
  open: 'open',
  investigating: 'investigating',
  identified: 'identified',
  resolved: 'resolved',
} as const;
