/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ForumLabelCreateKey } from './forumLabelCreateKey';

/**
 * Request schema for creating a forum label.
 */
export interface ForumLabelCreate {
  /** Stable label key. Generated from name when omitted. */
  key?: ForumLabelCreateKey;
  /**
     * Display name
     * @minLength 1
     * @maxLength 80
     */
  name: string;
  /**
     * Short description
     * @maxLength 200
     */
  description?: string;
  /**
     * Display hex color
     * @pattern ^#[0-9a-fA-F]{6}$
     */
  color: string;
}
