/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Thread workflow status
 */
export type ForumPostCreateStatus = typeof ForumPostCreateStatus[keyof typeof ForumPostCreateStatus];


export const ForumPostCreateStatus = {
  open: 'open',
  investigating: 'investigating',
  identified: 'identified',
  resolved: 'resolved',
} as const;
