/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ForumPostResponseTitle } from "./forumPostResponseTitle";
import type { ForumPostResponseParentId } from "./forumPostResponseParentId";

/**
 * Response schema for a forum post.
 */
export interface ForumPostResponse {
  /** Forum post document ID */
  id: string;
  /** Owning project identifier */
  project_id: string;
  /** Forum category key */
  category: string;
  /** Post author username */
  username: string;
  /** Thread title */
  title?: ForumPostResponseTitle;
  /** Markdown content */
  content: string;
  /** Parent forum post ID */
  parent_id?: ForumPostResponseParentId;
  /** Number of replies to this thread */
  reply_count?: number;
  /** Whether this thread is closed */
  is_closed?: boolean;
  /** Whether this post is archived/deleted */
  is_deleted?: boolean;
  /** When the post was created */
  created_at: string;
  /** When the post was last updated */
  updated_at: string;
}
