/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ForumCategoryUpdateName } from './forumCategoryUpdateName';
import type { ForumCategoryUpdateDescription } from './forumCategoryUpdateDescription';
import type { ForumCategoryUpdateColor } from './forumCategoryUpdateColor';
import type { ForumCategoryUpdateIcon } from './forumCategoryUpdateIcon';
import type { ForumCategoryUpdateSortOrder } from './forumCategoryUpdateSortOrder';
import type { ForumCategoryUpdateIsArchived } from './forumCategoryUpdateIsArchived';

/**
 * Request schema for updating a forum category.
 */
export interface ForumCategoryUpdate {
  /** Display name */
  name?: ForumCategoryUpdateName;
  /** Short description */
  description?: ForumCategoryUpdateDescription;
  /** Display color token */
  color?: ForumCategoryUpdateColor;
  /** Display icon token */
  icon?: ForumCategoryUpdateIcon;
  /** Display order */
  sort_order?: ForumCategoryUpdateSortOrder;
  /** Whether this category is hidden */
  is_archived?: ForumCategoryUpdateIsArchived;
}
