/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response schema for a forum label.
 */
export interface ForumLabelResponse {
  /** Stable label key */
  key: string;
  /** Display name */
  name: string;
  /** Short label description */
  description?: string;
  /** Display hex color */
  color: string;
  /** Whether this label is managed by the system */
  is_system?: boolean;
}
