/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ForumPostUpdateCategory } from './forumPostUpdateCategory';
import type { ForumPostUpdateTitle } from './forumPostUpdateTitle';
import type { ForumPostUpdateContentBlocksItem } from './forumPostUpdateContentBlocksItem';

/**
 * Request schema for updating a forum post.
 */
export interface ForumPostUpdate {
  /** Updated forum category key for root threads */
  category?: ForumPostUpdateCategory;
  /** Updated title for root threads */
  title?: ForumPostUpdateTitle;
  /**
   * Updated content
   * @minLength 1
   * @maxLength 8000
   */
  content: string;
  /** BlockNote document JSON. Source of truth for rich content; content is derived. */
  content_blocks?: ForumPostUpdateContentBlocksItem[];
}
