/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type GetDashboardAiInsightsParams = {
  /**
   * Optional task-name filter
   */
  task_name?: string | null;
  /**
   * If true, use only the latest result per task and target
   */
  latest_only?: boolean;
  /**
   * Dashboard selection mode; accepted for filter-state traceability
   */
  selection_mode?: string | null;
  /**
   * Dashboard lower time bound; accepted for filter-state traceability
   */
  start_at?: string | null;
  /**
   * Dashboard upper time bound; accepted for filter-state traceability
   */
  end_at?: string | null;
};
