/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type GetForumPostRepliesParams = {
/**
 * Number of replies to skip
 * @minimum 0
 */
skip?: number;
/**
 * Max replies to return
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};
