/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type GetHistoricalCouplingTaskResultsParams = {
/**
 * Chip ID
 */
chip_id: string;
/**
 * Task name
 */
task: string;
/**
 * Date in YYYYMMDD format
 */
date: string;
/**
 * Inclusive start time lower bound
 */
start_at?: string | null;
/**
 * Exclusive end time upper bound
 */
end_at?: string | null;
};
