/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * QDash Server
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { InputParameterValue } from "./inputParameterValue";

/**
 * Input parameter class.
 */
export interface InputParameter {
  unit?: string;
  value_type?: string;
  value?: InputParameterValue;
  description?: string;
}
