/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * GitHub PR URL (set on approve)
 */
export type IssueKnowledgeResponsePrUrl = string | null;
