/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { FlowSummary } from './flowSummary';

/**
 * Response for listing flows.
 */
export interface ListFlowsResponse {
  /** List of flow summaries */
  flows: FlowSummary[];
}
