/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { TaskFileBackend } from './taskFileBackend';

/**
 * Response model for listing task file backends.
 */
export interface ListTaskFileBackendsResponse {
  backends: TaskFileBackend[];
}
