/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ForumPostResponse } from './forumPostResponse';

/**
 * Paginated list of forum posts.
 */
export interface ListForumPostsResponse {
  posts: ForumPostResponse[];
  total: number;
  skip: number;
  limit: number;
}
