/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ChipSummaryResponse } from "./chipSummaryResponse";

/**
 * Response model for listing chips with summary info only.

Use this instead of ListChipsResponse when you don't need qubit/coupling data.
 */
export interface ListChipsSummaryResponse {
  chips: ChipSummaryResponse[];
  total?: number;
}
