/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ScheduleCronCalibResponse } from "./scheduleCronCalibResponse";

/**
 * ListCronScheduleResponse is a subclass of BaseModel.
 */
export interface ListCronScheduleResponse {
  schedules: ScheduleCronCalibResponse[];
}
