/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * A point selected from the source spectroscopy figure.
 */
export interface ManualCorrectionPoint {
  /** Selected frequency coordinate */
  x: number;
  /** Selected power coordinate */
  y: number;
}
