/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ManualParameterUpdateResponseProvenanceActivityId } from './manualParameterUpdateResponseProvenanceActivityId';

/**
 * Response from manual parameter update.
 */
export interface ManualParameterUpdateResponse {
  updated_count: number;
  /** Created ManualParameterEdit task result ID */
  task_id: string;
  /** Created manual edit execution ID */
  execution_id: string;
  provenance_activity_id?: ManualParameterUpdateResponseProvenanceActivityId;
}
