/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ManualEditItem } from "./manualEditItem";

/**
 * All manual edits for a qid.
 */
export interface ManualEditsResponse {
  qid: string;
  edits: ManualEditItem[];
}
