/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ManualParameterUpdateResponseProvenanceActivityId } from "./manualParameterUpdateResponseProvenanceActivityId";

/**
 * Response from manual parameter update.
 */
export interface ManualParameterUpdateResponse {
  updated_count: number;
  provenance_activity_id?: ManualParameterUpdateResponseProvenanceActivityId;
}
