/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Task result the corrected values come from. When set, the parameter names are checked against that result and the edit is linked to it in the provenance graph.
 */
export type ManualParameterUpdateRequestSourceTaskId = string | null;
