/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { MetricHistoryItemInputParametersAnyOfAnyOf } from './metricHistoryItemInputParametersAnyOfAnyOf';

export type MetricHistoryItemInputParametersAnyOf = {[key: string]: MetricHistoryItemInputParametersAnyOfAnyOf | string | number | boolean | unknown[] | null};
