/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { MetricHistoryItemOutputParametersAnyOfAnyOfDatabaseUpdatesItemRole } from './metricHistoryItemOutputParametersAnyOfAnyOfDatabaseUpdatesItemRole';

/**
 * One calibration database update produced from a task output.
 */
export type MetricHistoryItemOutputParametersAnyOfAnyOfDatabaseUpdatesItem = {
  parameter_name: string;
  role: MetricHistoryItemOutputParametersAnyOfAnyOfDatabaseUpdatesItemRole;
  previous_value?: unknown;
  updated_value?: unknown;
  updated?: boolean;
};
