/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { MetricHistoryItemValue } from "./metricHistoryItemValue";
import type { MetricHistoryItemTaskId } from "./metricHistoryItemTaskId";
import type { MetricHistoryItemCalibratedAt } from "./metricHistoryItemCalibratedAt";

/**
 * Single historical metric data point.
 */
export interface MetricHistoryItem {
  value: MetricHistoryItemValue;
  execution_id: string;
  task_id?: MetricHistoryItemTaskId;
  timestamp: string;
  calibrated_at?: MetricHistoryItemCalibratedAt;
}
