/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ModelConfigTemperature } from "./modelConfigTemperature";
import type { ModelConfigBaseUrl } from "./modelConfigBaseUrl";
import type { ModelConfigApiKeyEnv } from "./modelConfigApiKeyEnv";

/**
 * Model configuration for CopilotKit.
 */
export interface ModelConfig {
  provider?: string;
  name?: string;
  temperature?: ModelConfigTemperature;
  max_output_tokens?: number;
  base_url?: ModelConfigBaseUrl;
  api_key_env?: ModelConfigApiKeyEnv;
}
