/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { Task } from "./task";

export type MuxDetailResponseDetail = {
  [key: string]: { [key: string]: Task };
};
