/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Body for creating or updating a note comment.
 */
export interface NoteCommentRequest {
  /**
     * Comment text content
     * @maxLength 5000
     */
  content: string;
}
