/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { NoteEventResponseActorUserId } from './noteEventResponseActorUserId';
import type { NoteEventResponseExtra } from './noteEventResponseExtra';

/**
 * One row of the note audit log.
 */
export interface NoteEventResponse {
  project_id: string;
  chip_id: string;
  /** qubit | qubit_metric | coupling | coupling_metric | task_result */
  scope: string;
  target_id: string;
  metric_key?: string;
  /** upsert | delete */
  action: string;
  actor_user_id?: NoteEventResponseActorUserId;
  actor: string;
  content?: string;
  extra?: NoteEventResponseExtra;
  created_at: string;
}
