/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Body for upserting a note.
 */
export interface NoteUpsertRequest {
  /**
   * Note text content
   * @maxLength 5000
   */
  content: string;
}
