/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { OutputParameterModelValue } from "./outputParameterModelValue";

/**
 * Data model.

Attributes
----------
    qubit (dict[str, dict[str, float | int]]): The calibration data for qubits.
    coupling (dict[str, dict[str, float | int]]): The calibration data for couplings.
 */
export interface OutputParameterModel {
  value?: OutputParameterModelValue;
  value_type?: string;
  error?: number;
  unit?: string;
  description?: string;
  /** The time when the system information was created */
  calibrated_at?: string;
  execution_id?: string;
}
