/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Data model for a parameter.

Attributes
----------
    name (str): The name of the parameter.
    unit (str): The unit of the parameter.
    description (str): Detailed description of the parameter.
 */
export interface ParameterModel {
  /** The username of the user who created the parameter */
  username: string;
  /** The name of the parameter */
  name: string;
  /** The unit of the parameter */
  unit?: string;
  /** Detailed description of the parameter */
  description?: string;
}
