/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { PipelineCatalogResponseExample } from './pipelineCatalogResponseExample';
import type { PipelineCatalogResponseSpecSchema } from './pipelineCatalogResponseSpecSchema';
import type { PipelineCatalogResponseTasks } from './pipelineCatalogResponseTasks';
import type { PipelineStepTypeInfo } from './pipelineStepTypeInfo';

/**
 * Everything needed to write a spec for this project.
 */
export interface PipelineCatalogResponse {
  backend_name: string;
  step_types: PipelineStepTypeInfo[];
  one_qubit_modes: string[];
  /** Available task names by task_type ("qubit", "coupling", ...). */
  tasks: PipelineCatalogResponseTasks;
  /** JSON schema of CalibrationPipelineSpec. */
  spec_schema: PipelineCatalogResponseSpecSchema;
  example?: PipelineCatalogResponseExample;
}
