/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * One reason a spec cannot run as written.
 */
export interface PipelineProblem {
  /** Where in the spec, e.g. "steps[2].tasks[0]" or "targets.qids". */
  path: string;
  message: string;
}
