/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { QubitMetricsQubitFrequency } from "./qubitMetricsQubitFrequency";
import type { QubitMetricsAnharmonicity } from "./qubitMetricsAnharmonicity";
import type { QubitMetricsT1 } from "./qubitMetricsT1";
import type { QubitMetricsT2Echo } from "./qubitMetricsT2Echo";
import type { QubitMetricsT2Star } from "./qubitMetricsT2Star";
import type { QubitMetricsAverageReadoutFidelity } from "./qubitMetricsAverageReadoutFidelity";
import type { QubitMetricsX90GateFidelity } from "./qubitMetricsX90GateFidelity";
import type { QubitMetricsX180GateFidelity } from "./qubitMetricsX180GateFidelity";

/**
 * Single qubit metrics data.
 */
export interface QubitMetrics {
  qubit_frequency?: QubitMetricsQubitFrequency;
  anharmonicity?: QubitMetricsAnharmonicity;
  t1?: QubitMetricsT1;
  t2_echo?: QubitMetricsT2Echo;
  t2_star?: QubitMetricsT2Star;
  average_readout_fidelity?: QubitMetricsAverageReadoutFidelity;
  x90_gate_fidelity?: QubitMetricsX90GateFidelity;
  x180_gate_fidelity?: QubitMetricsX180GateFidelity;
}
