/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { QubitMetricsX180GateFidelityAnyOf } from "./qubitMetricsX180GateFidelityAnyOf";

export type QubitMetricsX180GateFidelity =
  QubitMetricsX180GateFidelityAnyOf | null;
