/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Task result to re-analyze. If omitted, the latest matching task result for the (chip_id, qid) is used.
 */
export type ReanalyzeResonatorSpectroscopyRequestSourceTaskId = string | null;
