/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Power level (dB) sampled for low-power peaks.
 */
export type ReanalyzeResonatorSpectroscopyParamsLowPower = number | null;
