/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * If true, retry after trimming the highest-power row when no f01 is found.
 */
export type ReanalyzeQubitSpectroscopyParamsRetryWithTrim = boolean | null;
