/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ReanalyzeQubitSpectroscopyParamsBinarizeThresholdSigmaPlus } from "./reanalyzeQubitSpectroscopyParamsBinarizeThresholdSigmaPlus";
import type { ReanalyzeQubitSpectroscopyParamsBinarizeThresholdSigmaMinus } from "./reanalyzeQubitSpectroscopyParamsBinarizeThresholdSigmaMinus";
import type { ReanalyzeQubitSpectroscopyParamsTopPower } from "./reanalyzeQubitSpectroscopyParamsTopPower";
import type { ReanalyzeQubitSpectroscopyParamsF01HeightMin } from "./reanalyzeQubitSpectroscopyParamsF01HeightMin";
import type { ReanalyzeQubitSpectroscopyParamsF12DistanceMin } from "./reanalyzeQubitSpectroscopyParamsF12DistanceMin";
import type { ReanalyzeQubitSpectroscopyParamsF12DistanceMax } from "./reanalyzeQubitSpectroscopyParamsF12DistanceMax";
import type { ReanalyzeQubitSpectroscopyParamsF12HeightMin } from "./reanalyzeQubitSpectroscopyParamsF12HeightMin";
import type { ReanalyzeQubitSpectroscopyParamsRetryWithTrim } from "./reanalyzeQubitSpectroscopyParamsRetryWithTrim";

/**
 * Optional analysis-parameter overrides for qubit spectroscopy.
 */
export interface ReanalyzeQubitSpectroscopyParams {
  binarize_threshold_sigma_plus?: ReanalyzeQubitSpectroscopyParamsBinarizeThresholdSigmaPlus;
  binarize_threshold_sigma_minus?: ReanalyzeQubitSpectroscopyParamsBinarizeThresholdSigmaMinus;
  top_power?: ReanalyzeQubitSpectroscopyParamsTopPower;
  f01_height_min?: ReanalyzeQubitSpectroscopyParamsF01HeightMin;
  f12_distance_min?: ReanalyzeQubitSpectroscopyParamsF12DistanceMin;
  f12_distance_max?: ReanalyzeQubitSpectroscopyParamsF12DistanceMax;
  f12_height_min?: ReanalyzeQubitSpectroscopyParamsF12HeightMin;
  /** If true, retry after trimming the highest-power row when no f01 is found. */
  retry_with_trim?: ReanalyzeQubitSpectroscopyParamsRetryWithTrim;
}
