/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ReanalyzeResonatorSpectroscopyRequestSourceTaskId } from "./reanalyzeResonatorSpectroscopyRequestSourceTaskId";
import type { ReanalyzeResonatorSpectroscopyParams } from "./reanalyzeResonatorSpectroscopyParams";

/**
 * Request body for re-running CheckResonatorSpectroscopy analysis.
 */
export interface ReanalyzeResonatorSpectroscopyRequest {
  /** Task result to re-analyze. If omitted, the latest matching task result for the (chip_id, qid) is used. */
  source_task_id?: ReanalyzeResonatorSpectroscopyRequestSourceTaskId;
  parameters?: ReanalyzeResonatorSpectroscopyParams;
}
