/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ReanalyzeOutputParameter } from './reanalyzeOutputParameter';

/**
 * One qubit whose calibration value would be updated by a reanalysis.
 */
export interface ReanalyzeAffectedQubit {
  qid: string;
  output_parameters: ReanalyzeOutputParameter[];
}
