/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response from the host Codex workflow editing bridge.
 */
export interface RunCodexAgentResponse {
  /** Edited Python code content */
  code: string;
  /** Codex final response or execution summary */
  summary?: string;
  /** Unified diff between original and edited code */
  diff?: string;
  /** Codex command that was executed */
  command: string[];
}
