/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Next scheduled run time (ISO format)
 */
export type ScheduleFlowResponseNextRun = string | null;
