/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { SeedImportResponseProvenanceActivityId } from './seedImportResponseProvenanceActivityId';
import type { SeedImportResultItem } from './seedImportResultItem';

/**
 * Response from seed import operation.
 */
export interface SeedImportResponse {
  chip_id: string;
  source: string;
  imported_count: number;
  skipped_count: number;
  error_count: number;
  results: SeedImportResultItem[];
  /** Activity ID for provenance tracking */
  provenance_activity_id?: SeedImportResponseProvenanceActivityId;
}
