/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * QDash Server
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ServerRoutersChipTaskNoteAnyOf } from "./serverRoutersChipTaskNoteAnyOf";

export type ServerRoutersChipTaskNote = ServerRoutersChipTaskNoteAnyOf | null;
