/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { StartSystemUpdateRequestExpectedCurrentVersion } from './startSystemUpdateRequestExpectedCurrentVersion';

/**
 * Start request guarded against stale status screens.
 */
export interface StartSystemUpdateRequest {
  expected_current_version?: StartSystemUpdateRequestExpectedCurrentVersion;
}
