/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { AgentActionType } from './agentActionType';
import type { SubmitAgentActionRequestTaskName } from './submitAgentActionRequestTaskName';
import type { SubmitAgentActionRequestParameterOverrides } from './submitAgentActionRequestParameterOverrides';

/**
 * Submit an action proposal for platform-side authorization.
 */
export interface SubmitAgentActionRequest {
  /**
   * @minLength 1
   * @maxLength 128
   */
  idempotency_key: string;
  /** @minimum 0 */
  expected_state_version: number;
  action_type: AgentActionType;
  task_name?: SubmitAgentActionRequestTaskName;
  qids?: string[];
  parameter_overrides?: SubmitAgentActionRequestParameterOverrides;
  /** @maxLength 5000 */
  diagnosis?: string;
}
