/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * System-wide runtime settings visible to administrators.
 */
export interface SystemSettingsResponse {
  slack_forum_notifications_enabled?: boolean;
  slack_webhook_configured?: boolean;
}
