/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { NoteModel } from "./noteModel";
import type { TargetNoteEntryMetricNotes } from "./targetNoteEntryMetricNotes";

/**
 * Per-target row for the dashboard summary (qubit or coupling).
 */
export interface TargetNoteEntry {
  target_id: string;
  note?: NoteModel;
  metric_notes?: TargetNoteEntryMetricNotes;
}
