/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { NoteModel } from './noteModel';

export type TargetNoteEntryMetricNotes = {[key: string]: NoteModel};
