/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { InputParameter } from "./inputParameter";

export type TaskResponseInputParameters = { [key: string]: InputParameter };
