/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { TaskResultOutputParametersAnyOfAnyOfSource } from './taskResultOutputParametersAnyOfAnyOfSource';
import type { TaskResultOutputParametersAnyOfAnyOfCalibratedAt } from './taskResultOutputParametersAnyOfAnyOfCalibratedAt';

/**
 * Output parameter persisted in task-result history with DB comparison metadata.
 */
export type TaskResultOutputParametersAnyOfAnyOf = {
  parameter_name?: string;
  qid_role?: string;
  source?: TaskResultOutputParametersAnyOfAnyOfSource;
  required?: boolean;
  value?: unknown;
  value_type?: string;
  error?: number;
  unit?: string;
  description?: string;
  calibrated_at?: TaskResultOutputParametersAnyOfAnyOfCalibratedAt;
  execution_id?: string;
  task_id?: string;
  previous_database_value?: unknown;
  database_updated?: boolean;
  [key: string]: unknown;
 };
