/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * QDash Server
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { EdgeInfo } from "./edgeInfo";
import type { TwoQubitCalibResponseTwoQubitCalibData } from "./twoQubitCalibResponseTwoQubitCalibData";

export interface TwoQubitCalibResponse {
  qpu_name: string;
  cooling_down_id: number;
  label: string;
  status: string;
  edge_info: EdgeInfo;
  two_qubit_calib_data: TwoQubitCalibResponseTwoQubitCalibData;
  created_at?: string;
  updated_at?: string;
}
