/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * QDash Server
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { TwoQubitCalibData } from "./twoQubitCalibData";

export type TwoQubitCalibSummaryTwoQubitCalibData = TwoQubitCalibData | null;
