/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Unread notification count.
 */
export interface UnreadNotificationCountResponse {
  /** @minimum 0 */
  unread_count: number;
}
