/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateCopilotChatSessionRequestContextAnyOf } from './updateCopilotChatSessionRequestContextAnyOf';

export type UpdateCopilotChatSessionRequestContext = UpdateCopilotChatSessionRequestContextAnyOf | null;
