/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UserProfileUpdateAvatarKey } from './userProfileUpdateAvatarKey';
import type { UserProfileUpdateDisplayName } from './userProfileUpdateDisplayName';

/**
 * Current user profile update model.
 */
export interface UserProfileUpdate {
  display_name?: UserProfileUpdateDisplayName;
  avatar_key?: UserProfileUpdateAvatarKey;
}
