/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UserCreatePassword } from "./userCreatePassword";
import type { UserCreateDisplayName } from "./userCreateDisplayName";
import type { UserCreateOrganization } from "./userCreateOrganization";
import type { UserCreateAvatarKey } from "./userCreateAvatarKey";

/**
 * User creation model for registration (admin only).
 */
export interface UserCreate {
  /** @pattern ^[a-z0-9][a-z0-9._-]{1,62}[a-z0-9]$ */
  username: string;
  password?: UserCreatePassword;
  display_name?: UserCreateDisplayName;
  organization?: UserCreateOrganization;
  avatar_key?: UserCreateAvatarKey;
  create_default_project?: boolean;
}
