/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UserFullName } from "./userFullName";
import type { UserDisabled } from "./userDisabled";

/**
 * User model for authentication and user management.
 */
export interface User {
  username: string;
  full_name?: UserFullName;
  disabled?: UserDisabled;
}
