/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChipNotesSummaryResponse,
  CreateCouplingNoteCommentParams,
  CreateQubitNoteCommentParams,
  DeleteCouplingMetricNoteParams,
  DeleteCouplingNoteCommentParams,
  DeleteCouplingNoteParams,
  DeleteQubitMetricNoteParams,
  DeleteQubitNoteCommentParams,
  DeleteQubitNoteParams,
  GetChipNotesSummaryParams,
  HTTPValidationError,
  ListChipNoteEventsParams,
  ListNoteEventsResponse,
  ListTargetNoteEventsParams,
  NoteCommentModel,
  NoteCommentRequest,
  NoteModel,
  NoteUpsertRequest,
  SearchNoteEventsParams,
  SuccessResponse,
  UpdateCouplingNoteCommentParams,
  UpdateQubitNoteCommentParams,
  UpsertCouplingMetricNoteParams,
  UpsertCouplingNoteParams,
  UpsertQubitMetricNoteParams,
  UpsertQubitNoteParams
} from '../../schemas';

import { customInstance } from '../../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Upsert the general note for a qubit
 */
export const upsertQubitNote = (
    chipId: string,
    qid: string,
    noteUpsertRequest: NoteUpsertRequest,
    params?: UpsertQubitNoteParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<NoteModel>(
      {url: `/chips/${chipId}/qubits/${qid}/note`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: noteUpsertRequest,
        params
    },
      options);
    }
  


export const getUpsertQubitNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertQubitNote>>, TError,{chipId: string;qid: string;data: NoteUpsertRequest;params?: UpsertQubitNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof upsertQubitNote>>, TError,{chipId: string;qid: string;data: NoteUpsertRequest;params?: UpsertQubitNoteParams}, TContext> => {

const mutationKey = ['upsertQubitNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertQubitNote>>, {chipId: string;qid: string;data: NoteUpsertRequest;params?: UpsertQubitNoteParams}> = (props) => {
          const {chipId,qid,data,params} = props ?? {};

          return  upsertQubitNote(chipId,qid,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertQubitNoteMutationResult = NonNullable<Awaited<ReturnType<typeof upsertQubitNote>>>
    export type UpsertQubitNoteMutationBody = NoteUpsertRequest
    export type UpsertQubitNoteMutationError = HTTPValidationError

    /**
 * @summary Upsert the general note for a qubit
 */
export const useUpsertQubitNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertQubitNote>>, TError,{chipId: string;qid: string;data: NoteUpsertRequest;params?: UpsertQubitNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertQubitNote>>,
        TError,
        {chipId: string;qid: string;data: NoteUpsertRequest;params?: UpsertQubitNoteParams},
        TContext
      > => {

      const mutationOptions = getUpsertQubitNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Clear the general note for a qubit
 */
export const deleteQubitNote = (
    chipId: string,
    qid: string,
    params?: DeleteQubitNoteParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SuccessResponse>(
      {url: `/chips/${chipId}/qubits/${qid}/note`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteQubitNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQubitNote>>, TError,{chipId: string;qid: string;params?: DeleteQubitNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteQubitNote>>, TError,{chipId: string;qid: string;params?: DeleteQubitNoteParams}, TContext> => {

const mutationKey = ['deleteQubitNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteQubitNote>>, {chipId: string;qid: string;params?: DeleteQubitNoteParams}> = (props) => {
          const {chipId,qid,params} = props ?? {};

          return  deleteQubitNote(chipId,qid,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteQubitNoteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteQubitNote>>>
    
    export type DeleteQubitNoteMutationError = HTTPValidationError

    /**
 * @summary Clear the general note for a qubit
 */
export const useDeleteQubitNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQubitNote>>, TError,{chipId: string;qid: string;params?: DeleteQubitNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteQubitNote>>,
        TError,
        {chipId: string;qid: string;params?: DeleteQubitNoteParams},
        TContext
      > => {

      const mutationOptions = getDeleteQubitNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Create a target summary note entry for a qubit
 */
export const createQubitNoteComment = (
    chipId: string,
    qid: string,
    noteCommentRequest: NoteCommentRequest,
    params?: CreateQubitNoteCommentParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<NoteCommentModel>(
      {url: `/chips/${chipId}/qubits/${qid}/note/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: noteCommentRequest,
        params, signal
    },
      options);
    }
  


export const getCreateQubitNoteCommentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createQubitNoteComment>>, TError,{chipId: string;qid: string;data: NoteCommentRequest;params?: CreateQubitNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createQubitNoteComment>>, TError,{chipId: string;qid: string;data: NoteCommentRequest;params?: CreateQubitNoteCommentParams}, TContext> => {

const mutationKey = ['createQubitNoteComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createQubitNoteComment>>, {chipId: string;qid: string;data: NoteCommentRequest;params?: CreateQubitNoteCommentParams}> = (props) => {
          const {chipId,qid,data,params} = props ?? {};

          return  createQubitNoteComment(chipId,qid,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateQubitNoteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof createQubitNoteComment>>>
    export type CreateQubitNoteCommentMutationBody = NoteCommentRequest
    export type CreateQubitNoteCommentMutationError = HTTPValidationError

    /**
 * @summary Create a target summary note entry for a qubit
 */
export const useCreateQubitNoteComment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createQubitNoteComment>>, TError,{chipId: string;qid: string;data: NoteCommentRequest;params?: CreateQubitNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createQubitNoteComment>>,
        TError,
        {chipId: string;qid: string;data: NoteCommentRequest;params?: CreateQubitNoteCommentParams},
        TContext
      > => {

      const mutationOptions = getCreateQubitNoteCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update a target summary note entry for a qubit
 */
export const updateQubitNoteComment = (
    chipId: string,
    qid: string,
    commentId: string,
    noteCommentRequest: NoteCommentRequest,
    params?: UpdateQubitNoteCommentParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<NoteCommentModel>(
      {url: `/chips/${chipId}/qubits/${qid}/note/comments/${commentId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: noteCommentRequest,
        params
    },
      options);
    }
  


export const getUpdateQubitNoteCommentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateQubitNoteComment>>, TError,{chipId: string;qid: string;commentId: string;data: NoteCommentRequest;params?: UpdateQubitNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateQubitNoteComment>>, TError,{chipId: string;qid: string;commentId: string;data: NoteCommentRequest;params?: UpdateQubitNoteCommentParams}, TContext> => {

const mutationKey = ['updateQubitNoteComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateQubitNoteComment>>, {chipId: string;qid: string;commentId: string;data: NoteCommentRequest;params?: UpdateQubitNoteCommentParams}> = (props) => {
          const {chipId,qid,commentId,data,params} = props ?? {};

          return  updateQubitNoteComment(chipId,qid,commentId,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateQubitNoteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof updateQubitNoteComment>>>
    export type UpdateQubitNoteCommentMutationBody = NoteCommentRequest
    export type UpdateQubitNoteCommentMutationError = HTTPValidationError

    /**
 * @summary Update a target summary note entry for a qubit
 */
export const useUpdateQubitNoteComment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateQubitNoteComment>>, TError,{chipId: string;qid: string;commentId: string;data: NoteCommentRequest;params?: UpdateQubitNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateQubitNoteComment>>,
        TError,
        {chipId: string;qid: string;commentId: string;data: NoteCommentRequest;params?: UpdateQubitNoteCommentParams},
        TContext
      > => {

      const mutationOptions = getUpdateQubitNoteCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a target summary note entry for a qubit
 */
export const deleteQubitNoteComment = (
    chipId: string,
    qid: string,
    commentId: string,
    params?: DeleteQubitNoteCommentParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SuccessResponse>(
      {url: `/chips/${chipId}/qubits/${qid}/note/comments/${commentId}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteQubitNoteCommentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQubitNoteComment>>, TError,{chipId: string;qid: string;commentId: string;params?: DeleteQubitNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteQubitNoteComment>>, TError,{chipId: string;qid: string;commentId: string;params?: DeleteQubitNoteCommentParams}, TContext> => {

const mutationKey = ['deleteQubitNoteComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteQubitNoteComment>>, {chipId: string;qid: string;commentId: string;params?: DeleteQubitNoteCommentParams}> = (props) => {
          const {chipId,qid,commentId,params} = props ?? {};

          return  deleteQubitNoteComment(chipId,qid,commentId,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteQubitNoteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteQubitNoteComment>>>
    
    export type DeleteQubitNoteCommentMutationError = HTTPValidationError

    /**
 * @summary Delete a target summary note entry for a qubit
 */
export const useDeleteQubitNoteComment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQubitNoteComment>>, TError,{chipId: string;qid: string;commentId: string;params?: DeleteQubitNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteQubitNoteComment>>,
        TError,
        {chipId: string;qid: string;commentId: string;params?: DeleteQubitNoteCommentParams},
        TContext
      > => {

      const mutationOptions = getDeleteQubitNoteCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Upsert a per-metric note for a qubit
 */
export const upsertQubitMetricNote = (
    chipId: string,
    qid: string,
    metricKey: string,
    noteUpsertRequest: NoteUpsertRequest,
    params?: UpsertQubitMetricNoteParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<NoteModel>(
      {url: `/chips/${chipId}/qubits/${qid}/metric-notes/${metricKey}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: noteUpsertRequest,
        params
    },
      options);
    }
  


export const getUpsertQubitMetricNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertQubitMetricNote>>, TError,{chipId: string;qid: string;metricKey: string;data: NoteUpsertRequest;params?: UpsertQubitMetricNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof upsertQubitMetricNote>>, TError,{chipId: string;qid: string;metricKey: string;data: NoteUpsertRequest;params?: UpsertQubitMetricNoteParams}, TContext> => {

const mutationKey = ['upsertQubitMetricNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertQubitMetricNote>>, {chipId: string;qid: string;metricKey: string;data: NoteUpsertRequest;params?: UpsertQubitMetricNoteParams}> = (props) => {
          const {chipId,qid,metricKey,data,params} = props ?? {};

          return  upsertQubitMetricNote(chipId,qid,metricKey,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertQubitMetricNoteMutationResult = NonNullable<Awaited<ReturnType<typeof upsertQubitMetricNote>>>
    export type UpsertQubitMetricNoteMutationBody = NoteUpsertRequest
    export type UpsertQubitMetricNoteMutationError = HTTPValidationError

    /**
 * @summary Upsert a per-metric note for a qubit
 */
export const useUpsertQubitMetricNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertQubitMetricNote>>, TError,{chipId: string;qid: string;metricKey: string;data: NoteUpsertRequest;params?: UpsertQubitMetricNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertQubitMetricNote>>,
        TError,
        {chipId: string;qid: string;metricKey: string;data: NoteUpsertRequest;params?: UpsertQubitMetricNoteParams},
        TContext
      > => {

      const mutationOptions = getUpsertQubitMetricNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a per-metric note for a qubit
 */
export const deleteQubitMetricNote = (
    chipId: string,
    qid: string,
    metricKey: string,
    params?: DeleteQubitMetricNoteParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SuccessResponse>(
      {url: `/chips/${chipId}/qubits/${qid}/metric-notes/${metricKey}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteQubitMetricNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQubitMetricNote>>, TError,{chipId: string;qid: string;metricKey: string;params?: DeleteQubitMetricNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteQubitMetricNote>>, TError,{chipId: string;qid: string;metricKey: string;params?: DeleteQubitMetricNoteParams}, TContext> => {

const mutationKey = ['deleteQubitMetricNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteQubitMetricNote>>, {chipId: string;qid: string;metricKey: string;params?: DeleteQubitMetricNoteParams}> = (props) => {
          const {chipId,qid,metricKey,params} = props ?? {};

          return  deleteQubitMetricNote(chipId,qid,metricKey,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteQubitMetricNoteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteQubitMetricNote>>>
    
    export type DeleteQubitMetricNoteMutationError = HTTPValidationError

    /**
 * @summary Delete a per-metric note for a qubit
 */
export const useDeleteQubitMetricNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQubitMetricNote>>, TError,{chipId: string;qid: string;metricKey: string;params?: DeleteQubitMetricNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteQubitMetricNote>>,
        TError,
        {chipId: string;qid: string;metricKey: string;params?: DeleteQubitMetricNoteParams},
        TContext
      > => {

      const mutationOptions = getDeleteQubitMetricNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Upsert the general note for a coupling
 */
export const upsertCouplingNote = (
    chipId: string,
    couplingId: string,
    noteUpsertRequest: NoteUpsertRequest,
    params?: UpsertCouplingNoteParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<NoteModel>(
      {url: `/chips/${chipId}/couplings/${couplingId}/note`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: noteUpsertRequest,
        params
    },
      options);
    }
  


export const getUpsertCouplingNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertCouplingNote>>, TError,{chipId: string;couplingId: string;data: NoteUpsertRequest;params?: UpsertCouplingNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof upsertCouplingNote>>, TError,{chipId: string;couplingId: string;data: NoteUpsertRequest;params?: UpsertCouplingNoteParams}, TContext> => {

const mutationKey = ['upsertCouplingNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertCouplingNote>>, {chipId: string;couplingId: string;data: NoteUpsertRequest;params?: UpsertCouplingNoteParams}> = (props) => {
          const {chipId,couplingId,data,params} = props ?? {};

          return  upsertCouplingNote(chipId,couplingId,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertCouplingNoteMutationResult = NonNullable<Awaited<ReturnType<typeof upsertCouplingNote>>>
    export type UpsertCouplingNoteMutationBody = NoteUpsertRequest
    export type UpsertCouplingNoteMutationError = HTTPValidationError

    /**
 * @summary Upsert the general note for a coupling
 */
export const useUpsertCouplingNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertCouplingNote>>, TError,{chipId: string;couplingId: string;data: NoteUpsertRequest;params?: UpsertCouplingNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertCouplingNote>>,
        TError,
        {chipId: string;couplingId: string;data: NoteUpsertRequest;params?: UpsertCouplingNoteParams},
        TContext
      > => {

      const mutationOptions = getUpsertCouplingNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Clear the general note for a coupling
 */
export const deleteCouplingNote = (
    chipId: string,
    couplingId: string,
    params?: DeleteCouplingNoteParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SuccessResponse>(
      {url: `/chips/${chipId}/couplings/${couplingId}/note`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteCouplingNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCouplingNote>>, TError,{chipId: string;couplingId: string;params?: DeleteCouplingNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCouplingNote>>, TError,{chipId: string;couplingId: string;params?: DeleteCouplingNoteParams}, TContext> => {

const mutationKey = ['deleteCouplingNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCouplingNote>>, {chipId: string;couplingId: string;params?: DeleteCouplingNoteParams}> = (props) => {
          const {chipId,couplingId,params} = props ?? {};

          return  deleteCouplingNote(chipId,couplingId,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCouplingNoteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCouplingNote>>>
    
    export type DeleteCouplingNoteMutationError = HTTPValidationError

    /**
 * @summary Clear the general note for a coupling
 */
export const useDeleteCouplingNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCouplingNote>>, TError,{chipId: string;couplingId: string;params?: DeleteCouplingNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCouplingNote>>,
        TError,
        {chipId: string;couplingId: string;params?: DeleteCouplingNoteParams},
        TContext
      > => {

      const mutationOptions = getDeleteCouplingNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Create a target summary note entry for a coupling
 */
export const createCouplingNoteComment = (
    chipId: string,
    couplingId: string,
    noteCommentRequest: NoteCommentRequest,
    params?: CreateCouplingNoteCommentParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<NoteCommentModel>(
      {url: `/chips/${chipId}/couplings/${couplingId}/note/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: noteCommentRequest,
        params, signal
    },
      options);
    }
  


export const getCreateCouplingNoteCommentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCouplingNoteComment>>, TError,{chipId: string;couplingId: string;data: NoteCommentRequest;params?: CreateCouplingNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCouplingNoteComment>>, TError,{chipId: string;couplingId: string;data: NoteCommentRequest;params?: CreateCouplingNoteCommentParams}, TContext> => {

const mutationKey = ['createCouplingNoteComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCouplingNoteComment>>, {chipId: string;couplingId: string;data: NoteCommentRequest;params?: CreateCouplingNoteCommentParams}> = (props) => {
          const {chipId,couplingId,data,params} = props ?? {};

          return  createCouplingNoteComment(chipId,couplingId,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCouplingNoteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof createCouplingNoteComment>>>
    export type CreateCouplingNoteCommentMutationBody = NoteCommentRequest
    export type CreateCouplingNoteCommentMutationError = HTTPValidationError

    /**
 * @summary Create a target summary note entry for a coupling
 */
export const useCreateCouplingNoteComment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCouplingNoteComment>>, TError,{chipId: string;couplingId: string;data: NoteCommentRequest;params?: CreateCouplingNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCouplingNoteComment>>,
        TError,
        {chipId: string;couplingId: string;data: NoteCommentRequest;params?: CreateCouplingNoteCommentParams},
        TContext
      > => {

      const mutationOptions = getCreateCouplingNoteCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update a target summary note entry for a coupling
 */
export const updateCouplingNoteComment = (
    chipId: string,
    couplingId: string,
    commentId: string,
    noteCommentRequest: NoteCommentRequest,
    params?: UpdateCouplingNoteCommentParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<NoteCommentModel>(
      {url: `/chips/${chipId}/couplings/${couplingId}/note/comments/${commentId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: noteCommentRequest,
        params
    },
      options);
    }
  


export const getUpdateCouplingNoteCommentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCouplingNoteComment>>, TError,{chipId: string;couplingId: string;commentId: string;data: NoteCommentRequest;params?: UpdateCouplingNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCouplingNoteComment>>, TError,{chipId: string;couplingId: string;commentId: string;data: NoteCommentRequest;params?: UpdateCouplingNoteCommentParams}, TContext> => {

const mutationKey = ['updateCouplingNoteComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCouplingNoteComment>>, {chipId: string;couplingId: string;commentId: string;data: NoteCommentRequest;params?: UpdateCouplingNoteCommentParams}> = (props) => {
          const {chipId,couplingId,commentId,data,params} = props ?? {};

          return  updateCouplingNoteComment(chipId,couplingId,commentId,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCouplingNoteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof updateCouplingNoteComment>>>
    export type UpdateCouplingNoteCommentMutationBody = NoteCommentRequest
    export type UpdateCouplingNoteCommentMutationError = HTTPValidationError

    /**
 * @summary Update a target summary note entry for a coupling
 */
export const useUpdateCouplingNoteComment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCouplingNoteComment>>, TError,{chipId: string;couplingId: string;commentId: string;data: NoteCommentRequest;params?: UpdateCouplingNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCouplingNoteComment>>,
        TError,
        {chipId: string;couplingId: string;commentId: string;data: NoteCommentRequest;params?: UpdateCouplingNoteCommentParams},
        TContext
      > => {

      const mutationOptions = getUpdateCouplingNoteCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a target summary note entry for a coupling
 */
export const deleteCouplingNoteComment = (
    chipId: string,
    couplingId: string,
    commentId: string,
    params?: DeleteCouplingNoteCommentParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SuccessResponse>(
      {url: `/chips/${chipId}/couplings/${couplingId}/note/comments/${commentId}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteCouplingNoteCommentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCouplingNoteComment>>, TError,{chipId: string;couplingId: string;commentId: string;params?: DeleteCouplingNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCouplingNoteComment>>, TError,{chipId: string;couplingId: string;commentId: string;params?: DeleteCouplingNoteCommentParams}, TContext> => {

const mutationKey = ['deleteCouplingNoteComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCouplingNoteComment>>, {chipId: string;couplingId: string;commentId: string;params?: DeleteCouplingNoteCommentParams}> = (props) => {
          const {chipId,couplingId,commentId,params} = props ?? {};

          return  deleteCouplingNoteComment(chipId,couplingId,commentId,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCouplingNoteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCouplingNoteComment>>>
    
    export type DeleteCouplingNoteCommentMutationError = HTTPValidationError

    /**
 * @summary Delete a target summary note entry for a coupling
 */
export const useDeleteCouplingNoteComment = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCouplingNoteComment>>, TError,{chipId: string;couplingId: string;commentId: string;params?: DeleteCouplingNoteCommentParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCouplingNoteComment>>,
        TError,
        {chipId: string;couplingId: string;commentId: string;params?: DeleteCouplingNoteCommentParams},
        TContext
      > => {

      const mutationOptions = getDeleteCouplingNoteCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Upsert a per-metric note for a coupling
 */
export const upsertCouplingMetricNote = (
    chipId: string,
    couplingId: string,
    metricKey: string,
    noteUpsertRequest: NoteUpsertRequest,
    params?: UpsertCouplingMetricNoteParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<NoteModel>(
      {url: `/chips/${chipId}/couplings/${couplingId}/metric-notes/${metricKey}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: noteUpsertRequest,
        params
    },
      options);
    }
  


export const getUpsertCouplingMetricNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertCouplingMetricNote>>, TError,{chipId: string;couplingId: string;metricKey: string;data: NoteUpsertRequest;params?: UpsertCouplingMetricNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof upsertCouplingMetricNote>>, TError,{chipId: string;couplingId: string;metricKey: string;data: NoteUpsertRequest;params?: UpsertCouplingMetricNoteParams}, TContext> => {

const mutationKey = ['upsertCouplingMetricNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertCouplingMetricNote>>, {chipId: string;couplingId: string;metricKey: string;data: NoteUpsertRequest;params?: UpsertCouplingMetricNoteParams}> = (props) => {
          const {chipId,couplingId,metricKey,data,params} = props ?? {};

          return  upsertCouplingMetricNote(chipId,couplingId,metricKey,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertCouplingMetricNoteMutationResult = NonNullable<Awaited<ReturnType<typeof upsertCouplingMetricNote>>>
    export type UpsertCouplingMetricNoteMutationBody = NoteUpsertRequest
    export type UpsertCouplingMetricNoteMutationError = HTTPValidationError

    /**
 * @summary Upsert a per-metric note for a coupling
 */
export const useUpsertCouplingMetricNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertCouplingMetricNote>>, TError,{chipId: string;couplingId: string;metricKey: string;data: NoteUpsertRequest;params?: UpsertCouplingMetricNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertCouplingMetricNote>>,
        TError,
        {chipId: string;couplingId: string;metricKey: string;data: NoteUpsertRequest;params?: UpsertCouplingMetricNoteParams},
        TContext
      > => {

      const mutationOptions = getUpsertCouplingMetricNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a per-metric note for a coupling
 */
export const deleteCouplingMetricNote = (
    chipId: string,
    couplingId: string,
    metricKey: string,
    params?: DeleteCouplingMetricNoteParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SuccessResponse>(
      {url: `/chips/${chipId}/couplings/${couplingId}/metric-notes/${metricKey}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteCouplingMetricNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCouplingMetricNote>>, TError,{chipId: string;couplingId: string;metricKey: string;params?: DeleteCouplingMetricNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCouplingMetricNote>>, TError,{chipId: string;couplingId: string;metricKey: string;params?: DeleteCouplingMetricNoteParams}, TContext> => {

const mutationKey = ['deleteCouplingMetricNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCouplingMetricNote>>, {chipId: string;couplingId: string;metricKey: string;params?: DeleteCouplingMetricNoteParams}> = (props) => {
          const {chipId,couplingId,metricKey,params} = props ?? {};

          return  deleteCouplingMetricNote(chipId,couplingId,metricKey,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCouplingMetricNoteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCouplingMetricNote>>>
    
    export type DeleteCouplingMetricNoteMutationError = HTTPValidationError

    /**
 * @summary Delete a per-metric note for a coupling
 */
export const useDeleteCouplingMetricNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCouplingMetricNote>>, TError,{chipId: string;couplingId: string;metricKey: string;params?: DeleteCouplingMetricNoteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCouplingMetricNote>>,
        TError,
        {chipId: string;couplingId: string;metricKey: string;params?: DeleteCouplingMetricNoteParams},
        TContext
      > => {

      const mutationOptions = getDeleteCouplingMetricNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get the user note for a task result
 */
export const getTaskNote = (
    taskId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<NoteModel>(
      {url: `/task-results/${taskId}/note`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTaskNoteQueryKey = (taskId?: string,) => {
    return [
    `/task-results/${taskId}/note`
    ] as const;
    }

    
export const getGetTaskNoteQueryOptions = <TData = Awaited<ReturnType<typeof getTaskNote>>, TError = HTTPValidationError>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskNote>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskNoteQueryKey(taskId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskNote>>> = ({ signal }) => getTaskNote(taskId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaskNote>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTaskNoteQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskNote>>>
export type GetTaskNoteQueryError = HTTPValidationError


export function useGetTaskNote<TData = Awaited<ReturnType<typeof getTaskNote>>, TError = HTTPValidationError>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskNote>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskNote>>,
          TError,
          Awaited<ReturnType<typeof getTaskNote>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTaskNote<TData = Awaited<ReturnType<typeof getTaskNote>>, TError = HTTPValidationError>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskNote>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskNote>>,
          TError,
          Awaited<ReturnType<typeof getTaskNote>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTaskNote<TData = Awaited<ReturnType<typeof getTaskNote>>, TError = HTTPValidationError>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskNote>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get the user note for a task result
 */

export function useGetTaskNote<TData = Awaited<ReturnType<typeof getTaskNote>>, TError = HTTPValidationError>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskNote>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTaskNoteQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Upsert the user note for a task result
 */
export const upsertTaskNote = (
    taskId: string,
    noteUpsertRequest: NoteUpsertRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<NoteModel>(
      {url: `/task-results/${taskId}/note`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: noteUpsertRequest
    },
      options);
    }
  


export const getUpsertTaskNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertTaskNote>>, TError,{taskId: string;data: NoteUpsertRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof upsertTaskNote>>, TError,{taskId: string;data: NoteUpsertRequest}, TContext> => {

const mutationKey = ['upsertTaskNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertTaskNote>>, {taskId: string;data: NoteUpsertRequest}> = (props) => {
          const {taskId,data} = props ?? {};

          return  upsertTaskNote(taskId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertTaskNoteMutationResult = NonNullable<Awaited<ReturnType<typeof upsertTaskNote>>>
    export type UpsertTaskNoteMutationBody = NoteUpsertRequest
    export type UpsertTaskNoteMutationError = HTTPValidationError

    /**
 * @summary Upsert the user note for a task result
 */
export const useUpsertTaskNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertTaskNote>>, TError,{taskId: string;data: NoteUpsertRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertTaskNote>>,
        TError,
        {taskId: string;data: NoteUpsertRequest},
        TContext
      > => {

      const mutationOptions = getUpsertTaskNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Clear the user note for a task result
 */
export const deleteTaskNote = (
    taskId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SuccessResponse>(
      {url: `/task-results/${taskId}/note`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteTaskNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTaskNote>>, TError,{taskId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTaskNote>>, TError,{taskId: string}, TContext> => {

const mutationKey = ['deleteTaskNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTaskNote>>, {taskId: string}> = (props) => {
          const {taskId} = props ?? {};

          return  deleteTaskNote(taskId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTaskNoteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTaskNote>>>
    
    export type DeleteTaskNoteMutationError = HTTPValidationError

    /**
 * @summary Clear the user note for a task result
 */
export const useDeleteTaskNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTaskNote>>, TError,{taskId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTaskNote>>,
        TError,
        {taskId: string},
        TContext
      > => {

      const mutationOptions = getDeleteTaskNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List all notes (qubit / coupling / task-result) on a chip
 */
export const getChipNotesSummary = (
    chipId: string,
    params?: GetChipNotesSummaryParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ChipNotesSummaryResponse>(
      {url: `/chips/${chipId}/notes-summary`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetChipNotesSummaryQueryKey = (chipId?: string,
    params?: GetChipNotesSummaryParams,) => {
    return [
    `/chips/${chipId}/notes-summary`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetChipNotesSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getChipNotesSummary>>, TError = HTTPValidationError>(chipId: string,
    params?: GetChipNotesSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChipNotesSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChipNotesSummaryQueryKey(chipId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChipNotesSummary>>> = ({ signal }) => getChipNotesSummary(chipId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(chipId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChipNotesSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetChipNotesSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getChipNotesSummary>>>
export type GetChipNotesSummaryQueryError = HTTPValidationError


export function useGetChipNotesSummary<TData = Awaited<ReturnType<typeof getChipNotesSummary>>, TError = HTTPValidationError>(
 chipId: string,
    params: undefined |  GetChipNotesSummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChipNotesSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipNotesSummary>>,
          TError,
          Awaited<ReturnType<typeof getChipNotesSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetChipNotesSummary<TData = Awaited<ReturnType<typeof getChipNotesSummary>>, TError = HTTPValidationError>(
 chipId: string,
    params?: GetChipNotesSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChipNotesSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipNotesSummary>>,
          TError,
          Awaited<ReturnType<typeof getChipNotesSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetChipNotesSummary<TData = Awaited<ReturnType<typeof getChipNotesSummary>>, TError = HTTPValidationError>(
 chipId: string,
    params?: GetChipNotesSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChipNotesSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List all notes (qubit / coupling / task-result) on a chip
 */

export function useGetChipNotesSummary<TData = Awaited<ReturnType<typeof getChipNotesSummary>>, TError = HTTPValidationError>(
 chipId: string,
    params?: GetChipNotesSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChipNotesSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetChipNotesSummaryQueryOptions(chipId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Chip-scoped note edit timeline
 */
export const listChipNoteEvents = (
    chipId: string,
    params?: ListChipNoteEventsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListNoteEventsResponse>(
      {url: `/chips/${chipId}/note-events`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListChipNoteEventsQueryKey = (chipId?: string,
    params?: ListChipNoteEventsParams,) => {
    return [
    `/chips/${chipId}/note-events`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListChipNoteEventsQueryOptions = <TData = Awaited<ReturnType<typeof listChipNoteEvents>>, TError = HTTPValidationError>(chipId: string,
    params?: ListChipNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChipNoteEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChipNoteEventsQueryKey(chipId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChipNoteEvents>>> = ({ signal }) => listChipNoteEvents(chipId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(chipId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listChipNoteEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListChipNoteEventsQueryResult = NonNullable<Awaited<ReturnType<typeof listChipNoteEvents>>>
export type ListChipNoteEventsQueryError = HTTPValidationError


export function useListChipNoteEvents<TData = Awaited<ReturnType<typeof listChipNoteEvents>>, TError = HTTPValidationError>(
 chipId: string,
    params: undefined |  ListChipNoteEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChipNoteEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChipNoteEvents>>,
          TError,
          Awaited<ReturnType<typeof listChipNoteEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListChipNoteEvents<TData = Awaited<ReturnType<typeof listChipNoteEvents>>, TError = HTTPValidationError>(
 chipId: string,
    params?: ListChipNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChipNoteEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChipNoteEvents>>,
          TError,
          Awaited<ReturnType<typeof listChipNoteEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListChipNoteEvents<TData = Awaited<ReturnType<typeof listChipNoteEvents>>, TError = HTTPValidationError>(
 chipId: string,
    params?: ListChipNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChipNoteEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Chip-scoped note edit timeline
 */

export function useListChipNoteEvents<TData = Awaited<ReturnType<typeof listChipNoteEvents>>, TError = HTTPValidationError>(
 chipId: string,
    params?: ListChipNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChipNoteEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListChipNoteEventsQueryOptions(chipId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Per-target note edit timeline
 */
export const listTargetNoteEvents = (
    params: ListTargetNoteEventsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListNoteEventsResponse>(
      {url: `/note-events/by-target`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListTargetNoteEventsQueryKey = (params?: ListTargetNoteEventsParams,) => {
    return [
    `/note-events/by-target`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListTargetNoteEventsQueryOptions = <TData = Awaited<ReturnType<typeof listTargetNoteEvents>>, TError = HTTPValidationError>(params: ListTargetNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTargetNoteEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTargetNoteEventsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTargetNoteEvents>>> = ({ signal }) => listTargetNoteEvents(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTargetNoteEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListTargetNoteEventsQueryResult = NonNullable<Awaited<ReturnType<typeof listTargetNoteEvents>>>
export type ListTargetNoteEventsQueryError = HTTPValidationError


export function useListTargetNoteEvents<TData = Awaited<ReturnType<typeof listTargetNoteEvents>>, TError = HTTPValidationError>(
 params: ListTargetNoteEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTargetNoteEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTargetNoteEvents>>,
          TError,
          Awaited<ReturnType<typeof listTargetNoteEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListTargetNoteEvents<TData = Awaited<ReturnType<typeof listTargetNoteEvents>>, TError = HTTPValidationError>(
 params: ListTargetNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTargetNoteEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTargetNoteEvents>>,
          TError,
          Awaited<ReturnType<typeof listTargetNoteEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListTargetNoteEvents<TData = Awaited<ReturnType<typeof listTargetNoteEvents>>, TError = HTTPValidationError>(
 params: ListTargetNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTargetNoteEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Per-target note edit timeline
 */

export function useListTargetNoteEvents<TData = Awaited<ReturnType<typeof listTargetNoteEvents>>, TError = HTTPValidationError>(
 params: ListTargetNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTargetNoteEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListTargetNoteEventsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Full-text search across note contents
 */
export const searchNoteEvents = (
    params: SearchNoteEventsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListNoteEventsResponse>(
      {url: `/note-events/search`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSearchNoteEventsQueryKey = (params?: SearchNoteEventsParams,) => {
    return [
    `/note-events/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchNoteEventsQueryOptions = <TData = Awaited<ReturnType<typeof searchNoteEvents>>, TError = HTTPValidationError>(params: SearchNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchNoteEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchNoteEventsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchNoteEvents>>> = ({ signal }) => searchNoteEvents(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchNoteEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SearchNoteEventsQueryResult = NonNullable<Awaited<ReturnType<typeof searchNoteEvents>>>
export type SearchNoteEventsQueryError = HTTPValidationError


export function useSearchNoteEvents<TData = Awaited<ReturnType<typeof searchNoteEvents>>, TError = HTTPValidationError>(
 params: SearchNoteEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchNoteEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchNoteEvents>>,
          TError,
          Awaited<ReturnType<typeof searchNoteEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSearchNoteEvents<TData = Awaited<ReturnType<typeof searchNoteEvents>>, TError = HTTPValidationError>(
 params: SearchNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchNoteEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchNoteEvents>>,
          TError,
          Awaited<ReturnType<typeof searchNoteEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSearchNoteEvents<TData = Awaited<ReturnType<typeof searchNoteEvents>>, TError = HTTPValidationError>(
 params: SearchNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchNoteEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Full-text search across note contents
 */

export function useSearchNoteEvents<TData = Awaited<ReturnType<typeof searchNoteEvents>>, TError = HTTPValidationError>(
 params: SearchNoteEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchNoteEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getSearchNoteEventsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



