/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type { ListParameterResponse } from "../../schemas";

/**
 * Fetch all parameters.

Args:
----
    current_user (User): The current user.

Returns: ListParameterResponse
-------
 * @summary Fetch all parameters
 */
export const fetchAllParameters = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ListParameterResponse>> => {
  return axios.get(`http://localhost:5715/parameter`, options);
};

export const getFetchAllParametersQueryKey = () => {
  return [`http://localhost:5715/parameter`] as const;
};

export const getFetchAllParametersQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchAllParameters>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof fetchAllParameters>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFetchAllParametersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchAllParameters>>
  > = ({ signal }) => fetchAllParameters({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchAllParameters>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type FetchAllParametersQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchAllParameters>>
>;
export type FetchAllParametersQueryError = AxiosError<unknown>;

export function useFetchAllParameters<
  TData = Awaited<ReturnType<typeof fetchAllParameters>>,
  TError = AxiosError<unknown>,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof fetchAllParameters>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof fetchAllParameters>>,
        TError,
        Awaited<ReturnType<typeof fetchAllParameters>>
      >,
      "initialData"
    >;
  axios?: AxiosRequestConfig;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useFetchAllParameters<
  TData = Awaited<ReturnType<typeof fetchAllParameters>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof fetchAllParameters>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof fetchAllParameters>>,
        TError,
        Awaited<ReturnType<typeof fetchAllParameters>>
      >,
      "initialData"
    >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useFetchAllParameters<
  TData = Awaited<ReturnType<typeof fetchAllParameters>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof fetchAllParameters>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch all parameters
 */

export function useFetchAllParameters<
  TData = Awaited<ReturnType<typeof fetchAllParameters>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof fetchAllParameters>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getFetchAllParametersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
