/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CryostatCreateRequest,
  CryostatResponse,
  CryostatUpdateRequest,
  HTTPValidationError,
  ListCryostatsResponse,
  SuccessResponse
} from '../../schemas';

import { customInstance } from '../../lib/api/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List all cryostats
 */
export const listCryostats = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ListCryostatsResponse>(
      {url: `/cryostats`, method: 'GET', signal
    },
      options);
    }




export const getListCryostatsQueryKey = () => {
    return [
    `/cryostats`
    ] as const;
    }


export const getListCryostatsQueryOptions = <TData = Awaited<ReturnType<typeof listCryostats>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCryostats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCryostatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCryostats>>> = ({ signal }) => listCryostats(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCryostats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCryostatsQueryResult = NonNullable<Awaited<ReturnType<typeof listCryostats>>>
export type ListCryostatsQueryError = HTTPValidationError


export function useListCryostats<TData = Awaited<ReturnType<typeof listCryostats>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCryostats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCryostats>>,
          TError,
          Awaited<ReturnType<typeof listCryostats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCryostats<TData = Awaited<ReturnType<typeof listCryostats>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCryostats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCryostats>>,
          TError,
          Awaited<ReturnType<typeof listCryostats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCryostats<TData = Awaited<ReturnType<typeof listCryostats>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCryostats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all cryostats
 */

export function useListCryostats<TData = Awaited<ReturnType<typeof listCryostats>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCryostats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCryostatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Create a cryostat
 */
export const createCryostat = (
    cryostatCreateRequest: CryostatCreateRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CryostatResponse>(
      {url: `/cryostats`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cryostatCreateRequest, signal
    },
      options);
    }




export const getCreateCryostatMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCryostat>>, TError,{data: CryostatCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCryostat>>, TError,{data: CryostatCreateRequest}, TContext> => {

const mutationKey = ['createCryostat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCryostat>>, {data: CryostatCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCryostat(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCryostatMutationResult = NonNullable<Awaited<ReturnType<typeof createCryostat>>>
    export type CreateCryostatMutationBody = CryostatCreateRequest
    export type CreateCryostatMutationError = HTTPValidationError

    /**
 * @summary Create a cryostat
 */
export const useCreateCryostat = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCryostat>>, TError,{data: CryostatCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCryostat>>,
        TError,
        {data: CryostatCreateRequest},
        TContext
      > => {
      return useMutation(getCreateCryostatMutationOptions(options), queryClient);
    }
    /**
 * @summary Get a cryostat by id
 */
export const getCryostat = (
    cryoId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CryostatResponse>(
      {url: `/cryostats/${cryoId}`, method: 'GET', signal
    },
      options);
    }




export const getGetCryostatQueryKey = (cryoId: string,) => {
    return [
    `/cryostats/${cryoId}`
    ] as const;
    }


export const getGetCryostatQueryOptions = <TData = Awaited<ReturnType<typeof getCryostat>>, TError = HTTPValidationError>(cryoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCryostat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCryostatQueryKey(cryoId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCryostat>>> = ({ signal }) => getCryostat(cryoId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: cryoId !== null && cryoId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCryostat>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCryostatQueryResult = NonNullable<Awaited<ReturnType<typeof getCryostat>>>
export type GetCryostatQueryError = HTTPValidationError


export function useGetCryostat<TData = Awaited<ReturnType<typeof getCryostat>>, TError = HTTPValidationError>(
 cryoId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCryostat>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCryostat>>,
          TError,
          Awaited<ReturnType<typeof getCryostat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCryostat<TData = Awaited<ReturnType<typeof getCryostat>>, TError = HTTPValidationError>(
 cryoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCryostat>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCryostat>>,
          TError,
          Awaited<ReturnType<typeof getCryostat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCryostat<TData = Awaited<ReturnType<typeof getCryostat>>, TError = HTTPValidationError>(
 cryoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCryostat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a cryostat by id
 */

export function useGetCryostat<TData = Awaited<ReturnType<typeof getCryostat>>, TError = HTTPValidationError>(
 cryoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCryostat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCryostatQueryOptions(cryoId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Update a cryostat
 */
export const updateCryostat = (
    cryoId: string,
    cryostatUpdateRequest: CryostatUpdateRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CryostatResponse>(
      {url: `/cryostats/${cryoId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: cryostatUpdateRequest, signal
    },
      options);
    }




export const getUpdateCryostatMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCryostat>>, TError,{cryoId: string;data: CryostatUpdateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCryostat>>, TError,{cryoId: string;data: CryostatUpdateRequest}, TContext> => {

const mutationKey = ['updateCryostat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCryostat>>, {cryoId: string;data: CryostatUpdateRequest}> = (props) => {
          const {cryoId,data} = props ?? {};

          return  updateCryostat(cryoId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateCryostatMutationResult = NonNullable<Awaited<ReturnType<typeof updateCryostat>>>
    export type UpdateCryostatMutationBody = CryostatUpdateRequest
    export type UpdateCryostatMutationError = HTTPValidationError

    /**
 * @summary Update a cryostat
 */
export const useUpdateCryostat = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCryostat>>, TError,{cryoId: string;data: CryostatUpdateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCryostat>>,
        TError,
        {cryoId: string;data: CryostatUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateCryostatMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a cryostat
 */
export const deleteCryostat = (
    cryoId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SuccessResponse>(
      {url: `/cryostats/${cryoId}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteCryostatMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCryostat>>, TError,{cryoId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCryostat>>, TError,{cryoId: string}, TContext> => {

const mutationKey = ['deleteCryostat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCryostat>>, {cryoId: string}> = (props) => {
          const {cryoId} = props ?? {};

          return  deleteCryostat(cryoId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCryostatMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCryostat>>>

    export type DeleteCryostatMutationError = HTTPValidationError

    /**
 * @summary Delete a cryostat
 */
export const useDeleteCryostat = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCryostat>>, TError,{cryoId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCryostat>>,
        TError,
        {cryoId: string},
        TContext
      > => {
      return useMutation(getDeleteCryostatMutationOptions(options), queryClient);
    }
