/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExecutePipelineRequest,
  ExecutePipelineResponse,
  GetCalibrationPipelineCatalogParams,
  HTTPValidationError,
  PipelineCatalogResponse,
  ValidatePipelineRequest,
  ValidatePipelineResponse
} from '../../schemas';

import { customInstance } from '../../lib/api/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Everything an agent needs to compose a spec: step types with their
 * dependencies and default tasks, the backend's tasks by type, and the JSON
 * schema of the spec.
 * @summary Step types, tasks, and spec schema for writing a calibration pipeline
 */
export const getCalibrationPipelineCatalog = (
    params?: GetCalibrationPipelineCatalogParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PipelineCatalogResponse>(
      {url: `/calibration-pipelines/catalog`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetCalibrationPipelineCatalogQueryKey = (params?: GetCalibrationPipelineCatalogParams,) => {
    return [
    `/calibration-pipelines/catalog`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetCalibrationPipelineCatalogQueryOptions = <TData = Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>, TError = HTTPValidationError>(params?: GetCalibrationPipelineCatalogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCalibrationPipelineCatalogQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>> = ({ signal }) => getCalibrationPipelineCatalog(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCalibrationPipelineCatalogQueryResult = NonNullable<Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>>
export type GetCalibrationPipelineCatalogQueryError = HTTPValidationError


export function useGetCalibrationPipelineCatalog<TData = Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>, TError = HTTPValidationError>(
 params: undefined |  GetCalibrationPipelineCatalogParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>,
          TError,
          Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalibrationPipelineCatalog<TData = Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>, TError = HTTPValidationError>(
 params?: GetCalibrationPipelineCatalogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>,
          TError,
          Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalibrationPipelineCatalog<TData = Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>, TError = HTTPValidationError>(
 params?: GetCalibrationPipelineCatalogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Step types, tasks, and spec schema for writing a calibration pipeline
 */

export function useGetCalibrationPipelineCatalog<TData = Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>, TError = HTTPValidationError>(
 params?: GetCalibrationPipelineCatalogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalibrationPipelineCatalog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCalibrationPipelineCatalogQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Dry run: reports every problem with a path into the spec, and the
 * resolved steps and tasks when it would run.
 * @summary Check a calibration pipeline spec without running it
 */
export const validateCalibrationPipeline = (
    validatePipelineRequest: ValidatePipelineRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ValidatePipelineResponse>(
      {url: `/calibration-pipelines/validate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: validatePipelineRequest, signal
    },
      options);
    }




export const getValidateCalibrationPipelineMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateCalibrationPipeline>>, TError,{data: ValidatePipelineRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof validateCalibrationPipeline>>, TError,{data: ValidatePipelineRequest}, TContext> => {

const mutationKey = ['validateCalibrationPipeline'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof validateCalibrationPipeline>>, {data: ValidatePipelineRequest}> = (props) => {
          const {data} = props ?? {};

          return  validateCalibrationPipeline(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ValidateCalibrationPipelineMutationResult = NonNullable<Awaited<ReturnType<typeof validateCalibrationPipeline>>>
    export type ValidateCalibrationPipelineMutationBody = ValidatePipelineRequest
    export type ValidateCalibrationPipelineMutationError = HTTPValidationError

    /**
 * @summary Check a calibration pipeline spec without running it
 */
export const useValidateCalibrationPipeline = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateCalibrationPipeline>>, TError,{data: ValidatePipelineRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof validateCalibrationPipeline>>,
        TError,
        {data: ValidatePipelineRequest},
        TContext
      > => {
      return useMutation(getValidateCalibrationPipelineMutationOptions(options), queryClient);
    }
    /**
 * Runs the spec as one execution through the worker's calibration-pipeline
 * deployment. A spec with problems is rejected with 422 and the same problem
 * list that /validate returns.
 * @summary Validate and run a calibration pipeline spec
 */
export const executeCalibrationPipeline = (
    executePipelineRequest: ExecutePipelineRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ExecutePipelineResponse>(
      {url: `/calibration-pipelines/execute`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: executePipelineRequest, signal
    },
      options);
    }




export const getExecuteCalibrationPipelineMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeCalibrationPipeline>>, TError,{data: ExecutePipelineRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof executeCalibrationPipeline>>, TError,{data: ExecutePipelineRequest}, TContext> => {

const mutationKey = ['executeCalibrationPipeline'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof executeCalibrationPipeline>>, {data: ExecutePipelineRequest}> = (props) => {
          const {data} = props ?? {};

          return  executeCalibrationPipeline(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExecuteCalibrationPipelineMutationResult = NonNullable<Awaited<ReturnType<typeof executeCalibrationPipeline>>>
    export type ExecuteCalibrationPipelineMutationBody = ExecutePipelineRequest
    export type ExecuteCalibrationPipelineMutationError = HTTPValidationError

    /**
 * @summary Validate and run a calibration pipeline spec
 */
export const useExecuteCalibrationPipeline = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeCalibrationPipeline>>, TError,{data: ExecutePipelineRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof executeCalibrationPipeline>>,
        TError,
        {data: ExecutePipelineRequest},
        TContext
      > => {
      return useMutation(getExecuteCalibrationPipelineMutationOptions(options), queryClient);
    }
