/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    // container: {
    //   center: true,
    //   padding: '2rem',
    //   screens: {
    //     DEFAULT: '100%',
    //     sm: '600px',
    //     md: '728px',
    //     lg: '984px',
    //     xl: '1240px',
    //     '2xl': '1536px',
    //   },
    // },
    extend: {},
  },
  daisyui: {
    themes: [
      {
        // wireframe: {
        //   ...require("daisyui/src/theming/themes")["wireframe"],
        //   primary: "#000000",
        //   secondary: "teal",
        //   accent: "#45E038",
        //   neutral: "teal",
        //   "base-100": "#F1F3F4",
        //   info: "#51d0ff",
        //   success: "#539b00",
        //   warning: "#bd8100",
        //   error: "#ff7487",
        // },
        light: {
          primary: "#1a365d",
          "primary-content": "#ffffff",
          secondary: "#2563eb",
          "secondary-content": "#ffffff",
          accent: "#059669",
          "accent-content": "#ffffff",
          neutral: "#1f2937",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f3f4f6",
          "base-300": "#e5e7eb",
          "base-content": "#1f2937",
          info: "#0284c7",
          "info-content": "#ffffff",
          success: "#059669",
          "success-content": "#ffffff",
          warning: "#d97706",
          "warning-content": "#ffffff",
          error: "#dc2626",
          "error-content": "#ffffff",
        },
      },
      {
        dark: {
          primary: "#60a5fa",
          "primary-content": "#1f2937",
          secondary: "#818cf8",
          "secondary-content": "#1f2937",
          accent: "#34d399",
          "accent-content": "#1f2937",
          neutral: "#6b7280",
          "neutral-content": "#f3f4f6",
          "base-100": "#1f2937",
          "base-200": "#111827",
          "base-300": "#374151",
          "base-content": "#f3f4f6",
          info: "#38bdf8",
          "info-content": "#1f2937",
          success: "#4ade80",
          "success-content": "#1f2937",
          warning: "#fbbf24",
          "warning-content": "#1f2937",
          error: "#f87171",
          "error-content": "#1f2937",
        },
      },
    ],
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("daisyui"),
    require("daisyui/src/theming/themes"),
  ],
};
