name: Secret Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  trufflehog:
    name: Trufflehog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified --exclude-paths .trufflehog-exclude-paths.txt
